# Traffix.id — LSTM Inference Pipeline

## 1. Install Dependencies

In [1]:
!pip install tensorflow joblib pandas numpy -q
!pip install tf-keras -q
print("Dependencies installed.")

Dependencies installed.

## 2. Imports

In [2]:
import os, json, math, warnings
import numpy as np
import pandas as pd
import joblib
import tensorflow as tf
from datetime import datetime, timedelta

warnings.filterwarnings('ignore')

print("Imports OK.")
print(f"TensorFlow version: {tf.__version__}")

Imports OK.
TensorFlow version: 2.20.0

## 3. Upload Artifacts

In [3]:
from google.colab import files as colab_files

ARTIFACTS_DIR = '/content/artifacts'
os.makedirs(ARTIFACTS_DIR, exist_ok=True)

print("Upload artifact:")
print("  1. best_lstm_15m.keras")
print("  2. best_lstm_2h.keras")
print("  3. best_lstm_4h.keras")
print("  4. feat_scaler.joblib")
print("  5. target_scalers.joblib")
print("  6. best_config.json")
print("  7. feature_columns.json")
print("  8. vehicle_count.csv  (output dari notebook YOLO inference)")
print()

uploaded = colab_files.upload()
for fname, data in uploaded.items():
    dest = os.path.join(ARTIFACTS_DIR, fname)
    with open(dest, 'wb') as f:
        f.write(data)
    print(f"Saved: {dest}")

Upload artifact:
  1. best_lstm_15m.keras
  2. best_lstm_2h.keras
  3. best_lstm_4h.keras
  4. feat_scaler.joblib
  5. target_scalers.joblib
  6. best_config.json
  7. feature_columns.json
  8. vehicle_count.csv  (output dari notebook YOLO inference)

Saving best_config.json to best_config.json
Saving best_lstm_2h.keras to best_lstm_2h.keras
Saving best_lstm_4h.keras to best_lstm_4h.keras
Saving best_lstm_15m.keras to best_lstm_15m.keras
Saving feat_scaler.joblib to feat_scaler.joblib
Saving feature_columns.json to feature_columns.json
Saving target_scalers.joblib to target_scalers.joblib
Saving vehicle_count.csv to vehicle_count.csv
Saved: /content/artifacts/best_config.json
Saved: /content/artifacts/best_lstm_2h.keras
Saved: /content/artifacts/best_lstm_4h.keras
Saved: /content/artifacts/best_lstm_15m.keras
Saved: /content/artifacts/feat_scaler.joblib
Saved: /content/artifacts/feature_columns.json
Saved: /content/artifacts/target_scalers.joblib
Saved: /content/artifacts/vehicle_count.csv

## 4. Runtime Configuration & Output Paths

In [4]:
OUTPUT_DIR = '/content/outputs'
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Daftar artifact wajib
REQUIRED_FILES = [
    'best_lstm_15m.keras', 'best_lstm_2h.keras', 'best_lstm_4h.keras',
    'feat_scaler.joblib', 'target_scalers.joblib',
    'best_config.json', 'feature_columns.json',
    'vehicle_count.csv',
]

missing = [f for f in REQUIRED_FILES if not os.path.exists(os.path.join(ARTIFACTS_DIR, f))]
if missing:
    print(f"[WARNING] File berikut belum diupload: {missing}")
else:
    print("[OK] Semua artifact yang diperlukan sudah tersedia.")

print(f"Output dir: {OUTPUT_DIR}")

[OK] Semua artifact yang diperlukan sudah tersedia.
Output dir: /content/outputs

## 5. Load LSTM Artifacts (Model 15m / 2h / 4h + Scalers)

In [5]:
with open(os.path.join(ARTIFACTS_DIR, 'best_config.json')) as f:
    config = json.load(f)

SEQ_LEN = config['seq_len']
print(f"Config: seq_len={SEQ_LEN}")

with open(os.path.join(ARTIFACTS_DIR, 'feature_columns.json')) as f:
    FEATURE_COLUMNS = json.load(f)
NUM_FEATURES = len(FEATURE_COLUMNS)
print(f"Features: {NUM_FEATURES} columns")

feat_scaler    = joblib.load(os.path.join(ARTIFACTS_DIR, 'feat_scaler.joblib'))
target_scalers = joblib.load(os.path.join(ARTIFACTS_DIR, 'target_scalers.joblib'))
print(f"Scalers loaded. target_scalers keys: {list(target_scalers.keys())}")

# MAPE per horizon.
HORIZON_MAPE = {
    '15m': config.get('test_mape_15m'),
    '2h':  config.get('test_mape_2h', 27.035),
    '4h':  config.get('test_mape_4h', 32.492),
}
print(f"MAPE per horizon: {HORIZON_MAPE}")

# Load 3 model LSTM (15m, 2h, 4h)
LSTM_MODELS = {}
for h, fname in [('15m', 'best_lstm_15m.keras'),
                  ('2h',  'best_lstm_2h.keras'),
                  ('4h',  'best_lstm_4h.keras')]:
    LSTM_MODELS[h] = tf.keras.models.load_model(
        os.path.join(ARTIFACTS_DIR, fname), compile=False)
    print(f"[OK] LSTM model '{h}' loaded from {fname} | input_shape={LSTM_MODELS[h].input_shape}")

print()
LSTM_MODELS['15m'].summary()

Config: seq_len=15
Features: 41 columns
Scalers loaded. target_scalers keys: ['15m', '2h', '4h']
MAPE per horizon: {'15m': 21.8059, '2h': 27.035, '4h': 32.492}
[OK] LSTM model '15m' loaded from best_lstm_15m.keras | input_shape=(None, 15, 41)
[OK] LSTM model '2h' loaded from best_lstm_2h.keras | input_shape=(None, 15, 41)
[OK] LSTM model '4h' loaded from best_lstm_4h.keras | input_shape=(None, 15, 41)

Model: "lstm_light"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input (InputLayer)              │ (None, 15, 41)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm1 (LSTM)                    │ (None, 15, 64)         │        27,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ drop1 (Dropout)                 │ (None, 15, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm2 (LSTM)                    │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense1 (Dense)                  │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ drop2 (Dropout)                 │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41,729 (163.00 KB)

 Trainable params: 41,729 (163.00 KB)

 Non-trainable params: 0 (0.00 B)

## 6. LSTM Sequence Builder (Training-Aligned Synthetic Sequence)

In [6]:
def row_id_to_seed(row_id):
    return abs(hash(row_id)) % (2**31)

def build_training_aligned_sequence(obs, seq_len, rng):
    vc   = float(obs.get('vehicle_count_1min', 30.0))
    vol  = vc * 60.0
    spd  = float(obs.get('avg_speed_kmh', 50.0))
    q    = float(obs.get('queue_length_veh', 0.0))
    den  = float(obs.get('density_percent', 20.0))

    # Reconstruct base datetime (step i=seq_len-1 is "now")
    try:
        obs_dt = datetime(
            int(obs.get('year', 2024)), int(obs.get('month', 5)),
            int(obs.get('day', 1)), int(obs.get('hour', 8)), int(obs.get('minute', 0))
        )
    except Exception:
        obs_dt = datetime(2024, 5, 1, int(obs.get('hour', 8)), int(obs.get('minute', 0)))

    # Step 1: Generate seq_len-step volume_veh_per_hour history
    # BUG-A FIX: when vol=0, keep history at 0 (no noise inflation)
    noise_pct = 0.04
    vols = []
    if vol <= 0:
        vols = [0.0] * seq_len
    else:
        for i in range(seq_len):
            ramp  = 0.70 + 0.30 * (i / max(seq_len - 1, 1))
            base  = vol * ramp
            noise = rng.normal(0, max(abs(base) * noise_pct, 5.0))
            vols.append(max(0.0, base + noise))
        vols[-1] = vol    # anchor last step to actual observation

    vol_s = np.array(vols)

    # BUG-B FIX: safe denominator prevents explosion when vol=0 but q or den > 0
    vol_denom = max(vol, 1.0)

    SPEED_BASE = max(spd, 10.0)
    VOL_BASE   = max(vol, 60.0)
    spds = [max(5.0, SPEED_BASE * (1.0 - 0.4 * (vol_s[i] - vol_s[-1]) / VOL_BASE))
            for i in range(seq_len)]
    spds[-1] = spd

    qs   = [q * (vol_s[i] / vol_denom) for i in range(seq_len)]
    qs[-1] = q
    dens = [min(100.0, den * (vol_s[i] / vol_denom)) for i in range(seq_len)]
    dens[-1] = den

    # Step 2: Build per-timestep feature rows
    rows = []
    for i in range(seq_len):
        vc_i  = vol_s[i] / 60.0
        vol_i = vol_s[i]
        spd_i = spds[i]
        q_i   = qs[i]
        den_i = dens[i]

        wait_i  = q_i * 0.5
        green_i = float(obs.get('green_seconds', 25.6))

        dv = vol_s[i] - vol_s[i-1] if i > 0 else 0.0

        def lv(lag): return float(vol_s[max(i - lag, 0)])
        lag1  = lv(1);  lag5  = lv(5)
        lag15 = lv(15); lag30 = lv(30); lag60 = lv(60)

        lag_spd15 = float(spds[max(i-15, 0)])
        lag_q15   = float(qs[max(i-15, 0)])

        w15 = vol_s[max(0, i-14):i+1]
        w60 = vol_s[max(0, i-59):i+1]

        # BUG-C FIX: reconstruct per-step timestamp
        # step i=seq_len-1 is "now"; earlier steps go back in time
        minutes_ago = (seq_len - 1) - i
        step_dt     = obs_dt - timedelta(minutes=minutes_ago)
        h_i         = step_dt.hour
        m_i         = step_dt.minute
        sin_i       = math.sin(2 * math.pi * h_i / 24)
        cos_i       = math.cos(2 * math.pi * h_i / 24)

        row = {
            'vehicle_count_1min':   vc_i,
            'volume_veh_per_hour':  vol_i,
            'avg_speed_kmh':        spd_i,
            'queue_length_veh':     q_i,
            'wait_time_min':        wait_i,
            'green_seconds':        green_i,
            'density_percent':      den_i,
            'weather_temp_c':       float(obs.get('weather_temp_c', 30.0)),
            'accident_count':       float(obs.get('accident_count', 0)),
            'roadwork_flag':        float(obs.get('roadwork_flag', 0)),
            'event_flag':           float(obs.get('event_flag', 0)),
            'hour':                 float(h_i),
            'minute':               float(m_i),
            'day':                  float(obs.get('day', 1)),
            'day_of_week':          float(obs.get('day_of_week', 1)),
            'month':                float(obs.get('month', 6)),
            'is_holiday':           float(obs.get('is_holiday', 0)),
            'is_weekend':           float(obs.get('is_weekend', 0)),
            'hour_sin':             sin_i,
            'hour_cos':             cos_i,
            'delta_volume':         dv,
            'lag_1':               lag1,
            'lag_5':               lag5,
            'lag_15':              lag15,
            'lag_30':              lag30,
            'lag_60':              lag60,
            'lag_speed_15':        lag_spd15,
            'lag_queue_15':        lag_q15,
            'roll_mean_15':        float(w15.mean()),
            'roll_std_15':         float(w15.std()) if len(w15) > 1 else 0.0,
            'roll_min_15':         float(w15.min()),
            'roll_max_15':         float(w15.max()),
            'roll_median_15':      float(np.median(w15)),
            'roll_mean_60':        float(w60.mean()),
            'roll_std_60':         float(w60.std()) if len(w60) > 1 else 0.0,
            'roll_min_60':         float(w60.min()),
            'roll_max_60':         float(w60.max()),
            'weather_condition_Clear':  float(obs.get('weather_condition_Clear', 1)),
            'weather_condition_Cloudy': float(obs.get('weather_condition_Cloudy', 0)),
            'weather_condition_Hot':    float(obs.get('weather_condition_Hot', 0)),
            'weather_condition_Rain':   float(obs.get('weather_condition_Rain', 0)),
        }
        rows.append(row)

    # Step 3: Assemble array in exact FEATURE_COLUMNS order
    arr = np.array([[r[col] for col in FEATURE_COLUMNS] for r in rows], dtype=np.float64)
    return arr    # shape: (seq_len, n_features)

print("build_training_aligned_sequence() ready.")

build_training_aligned_sequence() ready.

## 7. Multi-Horizon Prediction Function (15m / 2h / 4h)

In [7]:
def predict_from_obs_multi(obs, row_id, verbose=True):
    rng = np.random.default_rng(row_id_to_seed(row_id))
    seq = build_training_aligned_sequence(obs, SEQ_LEN, rng)

    expected_feat_count = len(FEATURE_COLUMNS)
    if seq.shape != (SEQ_LEN, expected_feat_count):
        raise ValueError(
            f"[ERROR] raw sequence shape {seq.shape} != "
            f"({SEQ_LEN}, {expected_feat_count}). Check FEATURE_COLUMNS."
        )

    if not np.isfinite(seq).all():
        seq = np.nan_to_num(seq, nan=0.0, posinf=0.0, neginf=0.0)

    scaled = feat_scaler.transform(seq)
    X = scaled.reshape(1, SEQ_LEN, NUM_FEATURES).astype(np.float32)

    results = {}
    for h, model in LSTM_MODELS.items():
        pred_scaled = model.predict(X, verbose=0)
        scaler_h = target_scalers[h]
        inv = float(scaler_h.inverse_transform(pred_scaled.reshape(-1, 1)).flatten()[0])
        results[h] = max(0.0, round(inv, 2))

    if verbose:
        print(f"    -> 15m={results['15m']:.1f} | 2h={results['2h']:.1f} | 4h={results['4h']:.1f} veh/hour")

    return results

print("predict_from_obs_multi() ready.")

predict_from_obs_multi() ready.

## 8. Sensitivity Test (Sanity Check)

In [8]:
print("=== LSTM SENSITIVITY TEST (15m / 2h / 4h) ===")
print("Expected: predictions vary proportionally with vehicle_count_1min")
print()

_base_hour = 8
_base_obs = {
    'avg_speed_kmh':    50.0,
    'queue_length_veh': 2.0,
    'density_percent':  20.0,
    'weather_temp_c':   30.0,
    'hour':             _base_hour,
    'minute':           0,
    'day':              18,
    'day_of_week':      0,
    'month':            5,
    'is_holiday':       0,
    'is_weekend':       0,
    'hour_sin':         float(np.sin(2*np.pi*_base_hour/24)),
    'hour_cos':         float(np.cos(2*np.pi*_base_hour/24)),
    'weather_condition_Clear': 1, 'weather_condition_Cloudy': 0,
    'weather_condition_Hot': 0,   'weather_condition_Rain': 0,
    'accident_count': 0, 'roadwork_flag': 0, 'event_flag': 0,
    'green_seconds': 25.6, 'wait_time_min': 1.0,
}

_scenarios = [
    ('A',   0, "empty road"),
    ('B',  20, "light traffic"),
    ('C',  40, "moderate traffic"),
    ('D',  80, "heavy traffic"),
    ('E', 120, "very heavy traffic"),
]

_res_15m, _res_2h, _res_4h, _vc_vals = [], [], [], []

print(f"  {'Scenario':<22} {'vc_1min':>8}  {'15m':>9}  {'2h':>9}  {'4h':>9}")
print(f"  {'-'*22} {'-'*8}  {'-'*9}  {'-'*9}  {'-'*9}")
for label, vc_val, desc in _scenarios:
    obs = dict(_base_obs)
    obs['vehicle_count_1min']  = float(vc_val)
    obs['volume_veh_per_hour'] = float(vc_val * 60)
    obs['queue_length_veh']    = max(0.0, vc_val * 0.15)
    obs['density_percent']     = min(100.0, vc_val / 1.7)
    obs['avg_speed_kmh']       = max(10.0, 65.0 - vc_val * 0.35)
    obs['wait_time_min']       = max(0.0, vc_val * 0.07)

    res = predict_from_obs_multi(obs, f"sensitivity_{label}", verbose=False)
    _res_15m.append(res['15m']); _res_2h.append(res['2h']); _res_4h.append(res['4h'])
    _vc_vals.append(vc_val)
    print(f"  {label}: {desc:<18} {vc_val:>8.0f}  {res['15m']:>9.1f}  {res['2h']:>9.1f}  {res['4h']:>9.1f}")

print()
for label_h, vals in [('15m', _res_15m), ('2h', _res_2h), ('4h', _res_4h)]:
    spread = max(vals) - min(vals)
    mean_v = sum(vals) / len(vals)
    rel = spread / max(abs(mean_v), 1.0)
    if rel < 0.05:
        print(f"[WARNING] Horizon {label_h}: predictions nearly constant "
              f"(spread={round(spread,1)}, {round(rel*100,1)}%).")
    else:
        print(f"[OK] Horizon {label_h}: spread={round(spread,1)} veh/hour "
              f"({round(rel*100,1)}% relative). Model responds to traffic load.")

print("\nLSTM helpers ready.")

=== LSTM SENSITIVITY TEST (15m / 2h / 4h) ===
Expected: predictions vary proportionally with vehicle_count_1min

  Scenario                vc_1min        15m         2h         4h
  ---------------------- --------  ---------  ---------  ---------
  A: empty road                0      350.0      514.1      752.1
  B: light traffic            20      967.4     1859.0     1630.6
  C: moderate traffic         40     2817.3     3255.7     2168.2
  D: heavy traffic            80     3540.9     2147.3     3284.3
  E: very heavy traffic      120     3784.3     1758.8     4024.4

[OK] Horizon 15m: spread=3434.3 veh/hour (149.8% relative). Model responds to traffic load.
[OK] Horizon 2h: spread=2741.6 veh/hour (143.8% relative). Model responds to traffic load.
[OK] Horizon 4h: spread=3272.3 veh/hour (138.0% relative). Model responds to traffic load.

LSTM helpers ready.

## 9. Load Vehicle Count Data (Output YOLO Inference)

In [9]:
VC_PATH = os.path.join(ARTIFACTS_DIR, 'vehicle_count.csv')
vc_df = pd.read_csv(VC_PATH, encoding='utf-8-sig')

print(f"Loaded  : {VC_PATH}")
print(f"Rows    : {len(vc_df)}")
print(f"Columns : {list(vc_df.columns)}")
vc_df.head()

Loaded  : /content/artifacts/vehicle_count.csv
Rows    : 100
Columns : ['camera_id', 'source_video', 'date', 'time', 'period', 'latitude', 'longitude', 'weather', 'weather_temp_c', 'vehicle_count', 'vehicle_count_1min', 'volume_veh_per_hour', 'avg_speed_kmh', 'density_percent', 'queue_length_veh', 'congestion_level', 'detected_video_path']

,camera_id,source_video,date,time,period,latitude,longitude,weather,weather_temp_c,vehicle_count,vehicle_count_1min,volume_veh_per_hour,avg_speed_kmh,density_percent,queue_length_veh,congestion_level,detected_video_path
0,CAM_002,pagi_cctv_001_20260518_070935.mp4,5/18/2026,6:09:33,Morning Rush,-6.213143,106.683766,Cloudy,25.6,23,72,4320,53.62,19.80,0,Low,/content/outputs/detected_videos/detected_pagi...
1,CAM_001,pagi_cctv_002_20260518_070954.mp4,5/18/2026,6:15:26,Morning Rush,-6.191151,106.744189,Cloudy,26.8,67,71,4260,40.17,51.03,1,Medium,/content/outputs/detected_videos/detected_pagi...
2,CAM_001,pagi_cctv_003_20260614_080117.mp4,6/14/2026,8:01:17,Morning Rush,-6.191151,106.744189,Cloudy,27.8,9,34,2040,46.51,7.59,0,Low,/content/outputs/detected_videos/detected_pagi...
3,CAM_011,pagi_cctv_004_20260518_071356.mp4,5/18/2026,6:18:01,Morning Rush,-6.191635,106.730124,Cloudy,25.6,63,73,4380,35.38,51.35,1,Medium,/content/outputs/detected_videos/detected_pagi...
4,CAM_007,pagi_cctv_005_20260614_080139.mp4,6/14/2026,8:01:39,Morning Rush,-6.202452,106.705216,Cloudy,27.8,54,85,5100,78.82,45.45,0,Low,/content/outputs/detected_videos/detected_pagi...

## 10. Green Signal Duration Estimator (Adaptive)

In [10]:
GREEN_BASE = 45.0   # detik — durasi default pada kondisi lalu lintas normal
GREEN_MIN  = 20.0   # detik — batas bawah durasi hijau
GREEN_MAX  = 90.0   # detik — batas atas durasi hijau

# Baseline kondisi "normal" yang menghasilkan GREEN_BASE
_DENSITY_BASELINE = 20.0   # %
_SPEED_BASELINE   = 50.0   # km/h

def compute_green_seconds(density_percent, queue_length_veh, avg_speed_kmh):
    density_adj = (density_percent - _DENSITY_BASELINE) * 0.30
    queue_adj   = queue_length_veh * 1.5
    speed_adj   = (_SPEED_BASELINE - avg_speed_kmh) * 0.20

    green = GREEN_BASE + density_adj + queue_adj + speed_adj
    return float(round(min(GREEN_MAX, max(GREEN_MIN, green)), 1))

# Sanity check: kondisi normal -> menghasilkan GREEN_BASE (45s)
_check = compute_green_seconds(_DENSITY_BASELINE, 0, _SPEED_BASELINE)
print(f"Sanity check (density=20%, queue=0, speed=50 km/h) -> green_seconds = {_check}s "
      f"(expected {GREEN_BASE}s)")

Sanity check (density=20%, queue=0, speed=50 km/h) -> green_seconds = 45.0s (expected 45.0s)

## 11. Build Per-Row Feature Observation (`obs`)

In [11]:
WEATHER_CONDITIONS = ['Clear', 'Cloudy', 'Hot', 'Rain']

def build_obs_from_row(row):
    # Parse date & time
    try:
        # Clean the time string by removing ' AM' or ' PM' if present
        time_str = str(row['time'])
        if ' AM' in time_str:
            time_str = time_str.replace(' AM', '')
        elif ' PM' in time_str:
            time_str = time_str.replace(' PM', '')

        dt_obj = datetime.strptime(f"{row['date']} {time_str}", '%m/%d/%Y %H:%M:%S')
    except Exception:
        dt_obj = datetime.now()

    hour, minute = dt_obj.hour, dt_obj.minute
    day, month   = dt_obj.day, dt_obj.month
    day_of_week  = dt_obj.weekday()
    is_weekend   = 1 if day_of_week >= 5 else 0

    # Weather one-hot
    weather_str = str(row.get('weather', 'Clear'))
    weather_onehot = {f'weather_condition_{c}': (1.0 if weather_str == c else 0.0)
                      for c in WEATHER_CONDITIONS}

    # Core traffic features dari hasil YOLO
    queue_length_veh = float(row.get('queue_length_veh', 0.0))
    avg_speed_kmh    = float(row.get('avg_speed_kmh', 0.0))
    density_percent  = float(row.get('density_percent', 0.0))

    # Derived features
    wait_time_min = round(queue_length_veh * 0.4, 2)
    green_seconds = compute_green_seconds(density_percent, queue_length_veh, avg_speed_kmh)

    obs = {
        'vehicle_count_1min':  float(row.get('vehicle_count_1min', 0.0)),
        'volume_veh_per_hour': float(row.get('volume_veh_per_hour', 0.0)),
        'avg_speed_kmh':       avg_speed_kmh,
        'queue_length_veh':    queue_length_veh,
        'wait_time_min':       wait_time_min,
        'green_seconds':       green_seconds,
        'density_percent':     density_percent,
        'weather_temp_c':      float(row.get('weather_temp_c', 30.0)),
        'accident_count':      float(row.get('accident_count', 0)),
        'roadwork_flag':       float(row.get('roadwork_flag', 0)),
        'event_flag':          float(row.get('event_flag', 0)),
        'is_holiday':          float(row.get('is_holiday', 0)),
        'hour':         hour,
        'minute':       minute,
        'day':          day,
        'day_of_week':  day_of_week,
        'month':        month,
        'is_weekend':   is_weekend,
        'hour_sin':     float(np.sin(2*np.pi*hour/24)),
        'hour_cos':     float(np.cos(2*np.pi*hour/24)),
    }
    obs.update(weather_onehot)
    return obs

print("build_obs_from_row() ready.")

build_obs_from_row() ready.

## 12. Run LSTM Predictions per Baris (15m / 2h / 4h)

In [12]:
print("=== LSTM PREDICTION (15m / 2h / 4h) PER ROW ===")

pred_15m, pred_2h, pred_4h = [], [], []
green_seconds_list = []
feature_rows = []

for idx, row in vc_df.iterrows():
    row_id = row.get('source_video', f'row_{idx}')
    obs = build_obs_from_row(row)

    print(f"\n  [{idx+1}/{len(vc_df)}] {row_id}")
    print(f"    vehicle_count_1min  = {obs['vehicle_count_1min']:.2f}")
    print(f"    volume_veh_per_hour = {obs['volume_veh_per_hour']:.2f}")
    print(f"    avg_speed_kmh       = {obs['avg_speed_kmh']:.2f}")
    print(f"    density_percent     = {obs['density_percent']:.2f}")
    print(f"    green_seconds       = {obs['green_seconds']:.1f}")

    try:
        res = predict_from_obs_multi(obs, row_id)
    except Exception as e:
        print(f"    [ERROR] {e}")
        res = {'15m': 0.0, '2h': 0.0, '4h': 0.0}

    pred_15m.append(res['15m'])
    pred_2h.append(res['2h'])
    pred_4h.append(res['4h'])
    green_seconds_list.append(obs['green_seconds'])

    # Simpan feature row (obs) + identitas baris untuk traffic_features CSV
    feat_row = {
        'camera_id':    row.get('camera_id', f'CAM_{idx+1:03d}'),
        'source_video': row.get('source_video', ''),
        'date':         row.get('date'),
        'time':         row.get('time'),
        'period':       row.get('period'),
    }
    feat_row.update(obs)
    feature_rows.append(feat_row)

vc_df['predicted_volume_15m'] = pred_15m
vc_df['predicted_volume_2h']  = pred_2h
vc_df['predicted_volume_4h']  = pred_4h
vc_df['green_seconds']        = green_seconds_list

print("\n[OK] Prediksi selesai untuk semua baris.")

=== LSTM PREDICTION (15m / 2h / 4h) PER ROW ===

  [1/100] pagi_cctv_001_20260518_070935.mp4
    vehicle_count_1min  = 72.00
    volume_veh_per_hour = 4320.00
    avg_speed_kmh       = 53.62
    density_percent     = 19.80
    green_seconds       = 44.2
    -> 15m=4506.8 | 2h=1585.8 | 4h=4978.1 veh/hour

  [2/100] pagi_cctv_002_20260518_070954.mp4
    vehicle_count_1min  = 71.00
    volume_veh_per_hour = 4260.00
    avg_speed_kmh       = 40.17
    density_percent     = 51.03
    green_seconds       = 57.8
    -> 15m=3870.7 | 2h=1628.0 | 4h=4986.5 veh/hour

  [3/100] pagi_cctv_003_20260614_080117.mp4
    vehicle_count_1min  = 34.00
    volume_veh_per_hour = 2040.00
    avg_speed_kmh       = 46.51
    density_percent     = 7.59
    green_seconds       = 42.0
    -> 15m=1750.7 | 2h=1215.8 | 4h=4722.3 veh/hour

  [4/100] pagi_cctv_004_20260518_071356.mp4
    vehicle_count_1min  = 73.00
    volume_veh_per_hour = 4380.00
    avg_speed_kmh       = 35.38
    density_percent     = 51.35
    green_seconds       = 58.8
    -> 15m=3832.9 | 2h=1632.3 | 4h=5003.0 veh/hour

  [5/100] pagi_cctv_005_20260614_080139.mp4
    vehicle_count_1min  = 85.00
    volume_veh_per_hour = 5100.00
    avg_speed_kmh       = 78.82
    density_percent     = 45.45
    green_seconds       = 46.9
    -> 15m=4123.9 | 2h=1507.9 | 4h=4727.1 veh/hour

  [6/100] pagi_cctv_006_20260518_071450.mp4
    vehicle_count_1min  = 90.00
    volume_veh_per_hour = 5400.00
    avg_speed_kmh       = 20.53
    density_percent     = 56.51
    green_seconds       = 90.0
    -> 15m=3183.6 | 2h=1678.7 | 4h=4930.2 veh/hour

  [7/100] pagi_cctv_007_20260614_080221.mp4
    vehicle_count_1min  = 83.00
    volume_veh_per_hour = 4980.00
    avg_speed_kmh       = 39.35
    density_percent     = 50.84
    green_seconds       = 57.9
    -> 15m=4035.8 | 2h=1624.5 | 4h=4751.3 veh/hour

  [8/100] pagi_cctv_008_20260614_083937.mp4
    vehicle_count_1min  = 80.00
    volume_veh_per_hour = 4800.00
    avg_speed_kmh       = 70.58
    density_percent     = 51.00
    green_seconds       = 53.2
    -> 15m=3503.3 | 2h=1480.0 | 4h=4737.9 veh/hour

  [9/100] pagi_cctv_009_20260518_071625.mp4
    vehicle_count_1min  = 99.00
    volume_veh_per_hour = 5940.00
    avg_speed_kmh       = 52.23
    density_percent     = 20.01
    green_seconds       = 44.6
    -> 15m=5143.1 | 2h=1825.2 | 4h=4752.0 veh/hour

  [10/100] pagi_cctv_010_20260614_084252.mp4
    vehicle_count_1min  = 0.00
    volume_veh_per_hour = 0.00
    avg_speed_kmh       = 80.00
    density_percent     = 0.00
    green_seconds       = 33.0
    -> 15m=214.8 | 2h=175.6 | 4h=253.0 veh/hour

  [11/100] pagi_cctv_011_20260614_090616.mp4
    vehicle_count_1min  = 0.00
    volume_veh_per_hour = 0.00
    avg_speed_kmh       = 80.00
    density_percent     = 0.00
    green_seconds       = 33.0
    -> 15m=214.8 | 2h=175.6 | 4h=253.0 veh/hour

  [12/100] pagi_cctv_012_20260614_090310.mp4
    vehicle_count_1min  = 84.00
    volume_veh_per_hour = 5040.00
    avg_speed_kmh       = 74.37
    density_percent     = 51.05
    green_seconds       = 53.9
    -> 15m=3431.2 | 2h=1475.5 | 4h=4677.0 veh/hour

  [13/100] pagi_cctv_013_20260614_081117.mp4
    vehicle_count_1min  = 92.00
    volume_veh_per_hour = 5520.00
    avg_speed_kmh       = 80.99
    density_percent     = 51.20
    green_seconds       = 54.2
    -> 15m=3651.5 | 2h=1524.0 | 4h=4474.6 veh/hour

  [14/100] pagi_cctv_014_20260518_072255.mp4
    vehicle_count_1min  = 131.00
    volume_veh_per_hour = 7860.00
    avg_speed_kmh       = 28.49
    density_percent     = 31.96
    green_seconds       = 55.9
    -> 15m=5038.5 | 2h=1800.5 | 4h=4425.1 veh/hour

  [15/100] pagi_cctv_015_20260518_072703.mp4
    vehicle_count_1min  = 32.00
    volume_veh_per_hour = 1920.00
    avg_speed_kmh       = 23.29
    density_percent     = 56.44
    green_seconds       = 90.0
    -> 15m=1456.7 | 2h=1452.8 | 4h=4424.6 veh/hour

  [16/100] pagi_cctv_016_20260614_084327.mp4
    vehicle_count_1min  = 59.00
    volume_veh_per_hour = 3540.00
    avg_speed_kmh       = 80.88
    density_percent     = 28.52
    green_seconds       = 41.4
    -> 15m=3190.8 | 2h=1704.7 | 4h=4768.4 veh/hour

  [17/100] pagi_cctv_017_20260614_090631.mp4
    vehicle_count_1min  = 68.00
    volume_veh_per_hour = 4080.00
    avg_speed_kmh       = 64.79
    density_percent     = 50.31
    green_seconds       = 51.1
    -> 15m=3395.7 | 2h=1467.2 | 4h=4897.2 veh/hour

  [18/100] pagi_cctv_018_20260614_090735.mp4
    vehicle_count_1min  = 25.00
    volume_veh_per_hour = 1500.00
    avg_speed_kmh       = 55.19
    density_percent     = 9.23
    green_seconds       = 40.7
    -> 15m=422.7 | 2h=1150.5 | 4h=3982.8 veh/hour

  [19/100] pagi_cctv_019_20260614_080343.mp4
    vehicle_count_1min  = 69.00
    volume_veh_per_hour = 4140.00
    avg_speed_kmh       = 86.07
    density_percent     = 51.01
    green_seconds       = 48.6
    -> 15m=3252.9 | 2h=1310.0 | 4h=4580.5 veh/hour

  [20/100] pagi_cctv_020_20260614_084403.mp4
    vehicle_count_1min  = 75.00
    volume_veh_per_hour = 4500.00
    avg_speed_kmh       = 96.51
    density_percent     = 13.62
    green_seconds       = 33.8
    -> 15m=3944.5 | 2h=1955.0 | 4h=4289.9 veh/hour

  [21/100] pagi_cctv_021_20260614_090559.mp4
    vehicle_count_1min  = 137.00
    volume_veh_per_hour = 8220.00
    avg_speed_kmh       = 48.38
    density_percent     = 27.79
    green_seconds       = 47.7
    -> 15m=5472.5 | 2h=1811.9 | 4h=4647.3 veh/hour

  [22/100] pagi_cctv_022_20260614_090032.mp4
    vehicle_count_1min  = 71.00
    volume_veh_per_hour = 4260.00
    avg_speed_kmh       = 81.94
    density_percent     = 50.34
    green_seconds       = 47.7
    -> 15m=3423.5 | 2h=1350.9 | 4h=4656.8 veh/hour

  [23/100] pagi_cctv_023_20260614_090010.mp4
    vehicle_count_1min  = 36.00
    volume_veh_per_hour = 2160.00
    avg_speed_kmh       = 71.39
    density_percent     = 9.39
    green_seconds       = 37.5
    -> 15m=1006.3 | 2h=1936.7 | 4h=4151.1 veh/hour

  [24/100] pagi_cctv_024_20260614_083635.mp4
    vehicle_count_1min  = 78.00
    volume_veh_per_hour = 4680.00
    avg_speed_kmh       = 76.15
    density_percent     = 51.39
    green_seconds       = 59.7
    -> 15m=2841.9 | 2h=1454.0 | 4h=4632.9 veh/hour

  [25/100] pagi_cctv_025_20260614_085807.mp4
    vehicle_count_1min  = 126.00
    volume_veh_per_hour = 7560.00
    avg_speed_kmh       = 39.04
    density_percent     = 51.21
    green_seconds       = 65.6
    -> 15m=4592.4 | 2h=1805.2 | 4h=4628.4 veh/hour

  [26/100] pagi_cctv_026_20260614_083559.mp4
    vehicle_count_1min  = 63.00
    volume_veh_per_hour = 3780.00
    avg_speed_kmh       = 64.57
    density_percent     = 32.08
    green_seconds       = 45.7
    -> 15m=3525.4 | 2h=1437.9 | 4h=4966.6 veh/hour

  [27/100] pagi_cctv_027_20260614_085504.mp4
    vehicle_count_1min  = 167.00
    volume_veh_per_hour = 10020.00
    avg_speed_kmh       = 59.95
    density_percent     = 51.44
    green_seconds       = 58.4
    -> 15m=5320.8 | 2h=1896.4 | 4h=4448.5 veh/hour

  [28/100] pagi_cctv_028_20260614_083354.mp4
    vehicle_count_1min  = 81.00
    volume_veh_per_hour = 4860.00
    avg_speed_kmh       = 78.91
    density_percent     = 50.32
    green_seconds       = 48.3
    -> 15m=3790.3 | 2h=1447.1 | 4h=4675.0 veh/hour

  [29/100] siang_cctv_001_20260518_163906.mp4
    vehicle_count_1min  = 92.00
    volume_veh_per_hour = 5520.00
    avg_speed_kmh       = 54.74
    density_percent     = 51.31
    green_seconds       = 63.9
    -> 15m=3571.9 | 2h=1661.2 | 4h=4752.9 veh/hour

  [30/100] siang_cctv_002_20260614_163126.mp4
    vehicle_count_1min  = 215.00
    volume_veh_per_hour = 12900.00
    avg_speed_kmh       = 34.16
    density_percent     = 51.22
    green_seconds       = 59.0
    -> 15m=5294.1 | 2h=1719.5 | 4h=4577.7 veh/hour

  [31/100] siang_cctv_003_20260518_165921.mp4
    vehicle_count_1min  = 7.00
    volume_veh_per_hour = 420.00
    avg_speed_kmh       = 6.61
    density_percent     = 26.47
    green_seconds       = 70.6
    -> 15m=970.6 | 2h=1474.8 | 4h=3790.8 veh/hour

  [32/100] siang_cctv_004_20260518_170659.mp4
    vehicle_count_1min  = 248.00
    volume_veh_per_hour = 14880.00
    avg_speed_kmh       = 29.31
    density_percent     = 52.24
    green_seconds       = 60.3
    -> 15m=4965.4 | 2h=1714.9 | 4h=4722.2 veh/hour

  [33/100] siang_cctv_005_20260518_171425.mp4
    vehicle_count_1min  = 139.00
    volume_veh_per_hour = 8340.00
    avg_speed_kmh       = 22.84
    density_percent     = 57.54
    green_seconds       = 90.0
    -> 15m=4073.9 | 2h=1784.7 | 4h=4665.1 veh/hour

  [34/100] siang_cctv_006_20260614_170915.mp4
    vehicle_count_1min  = 171.00
    volume_veh_per_hour = 10260.00
    avg_speed_kmh       = 38.76
    density_percent     = 52.27
    green_seconds       = 68.9
    -> 15m=5172.8 | 2h=1765.1 | 4h=4565.3 veh/hour

  [35/100] siang_cctv_007_20260518_160452.mp4
    vehicle_count_1min  = 117.00
    volume_veh_per_hour = 7020.00
    avg_speed_kmh       = 57.98
    density_percent     = 50.80
    green_seconds       = 55.6
    -> 15m=4723.0 | 2h=1949.6 | 4h=4657.3 veh/hour

  [36/100] siang_cctv_008_20260518_151934.mp4
    vehicle_count_1min  = 129.00
    volume_veh_per_hour = 7740.00
    avg_speed_kmh       = 71.71
    density_percent     = 14.10
    green_seconds       = 38.9
    -> 15m=5072.4 | 2h=1633.7 | 4h=4554.0 veh/hour

  [37/100] siang_cctv_009_20260614_170730.mp4
    vehicle_count_1min  = 155.00
    volume_veh_per_hour = 9300.00
    avg_speed_kmh       = 65.44
    density_percent     = 50.91
    green_seconds       = 52.7
    -> 15m=5385.2 | 2h=1807.3 | 4h=4415.9 veh/hour

  [38/100] siang_cctv_010_20260614_171050.mp4
    vehicle_count_1min  = 114.00
    volume_veh_per_hour = 6840.00
    avg_speed_kmh       = 70.12
    density_percent     = 51.46
    green_seconds       = 62.4
    -> 15m=4064.4 | 2h=1739.0 | 4h=4540.7 veh/hour

  [39/100] siang_cctv_011_20260614_171352.mp4
    vehicle_count_1min  = 3.00
    volume_veh_per_hour = 180.00
    avg_speed_kmh       = 2.46
    density_percent     = 2.11
    green_seconds       = 49.1
    -> 15m=1180.3 | 2h=1591.7 | 4h=4011.6 veh/hour

  [40/100] siang_cctv_012_20260614_165224.mp4
    vehicle_count_1min  = 100.00
    volume_veh_per_hour = 6000.00
    avg_speed_kmh       = 34.27
    density_percent     = 14.48
    green_seconds       = 48.0
    -> 15m=4883.8 | 2h=1692.9 | 4h=4432.1 veh/hour

  [41/100] siang_cctv_013_20260614_171437.mp4
    vehicle_count_1min  = 307.00
    volume_veh_per_hour = 18420.00
    avg_speed_kmh       = 46.62
    density_percent     = 51.97
    green_seconds       = 56.8
    -> 15m=5098.8 | 2h=1728.5 | 4h=4196.7 veh/hour

  [42/100] siang_cctv_016_20260614_171739.mp4
    vehicle_count_1min  = 55.00
    volume_veh_per_hour = 3300.00
    avg_speed_kmh       = 75.30
    density_percent     = 0.85
    green_seconds       = 34.2
    -> 15m=3236.0 | 2h=1909.7 | 4h=4171.4 veh/hour

  [43/100] siang_cctv_017_20260614_171746.mp4
    vehicle_count_1min  = 209.00
    volume_veh_per_hour = 12540.00
    avg_speed_kmh       = 36.96
    density_percent     = 50.84
    green_seconds       = 58.4
    -> 15m=5385.9 | 2h=1718.3 | 4h=4498.9 veh/hour

  [44/100] siang_cctv_018_20260614_171903.mp4
    vehicle_count_1min  = 44.00
    volume_veh_per_hour = 2640.00
    avg_speed_kmh       = 30.52
    density_percent     = 22.83
    green_seconds       = 52.7
    -> 15m=3022.4 | 2h=1375.2 | 4h=5000.9 veh/hour

  [45/100] siang_cctv_019_20260614_172002.mp4
    vehicle_count_1min  = 83.00
    volume_veh_per_hour = 4980.00
    avg_speed_kmh       = 21.15
    density_percent     = 56.98
    green_seconds       = 90.0
    -> 15m=3075.7 | 2h=1732.9 | 4h=5026.5 veh/hour

  [46/100] siang_cctv_020_20260614_165923.mp4
    vehicle_count_1min  = 200.00
    volume_veh_per_hour = 12000.00
    avg_speed_kmh       = 41.53
    density_percent     = 49.92
    green_seconds       = 58.7
    -> 15m=5400.8 | 2h=1717.0 | 4h=4408.2 veh/hour

  [47/100] siang_cctv_021_20260614_163509.mp4
    vehicle_count_1min  = 154.00
    volume_veh_per_hour = 9240.00
    avg_speed_kmh       = 64.29
    density_percent     = 51.29
    green_seconds       = 57.5
    -> 15m=5268.1 | 2h=1860.4 | 4h=4395.0 veh/hour

  [48/100] siang_cctv_022_20260614_163451.mp4
    vehicle_count_1min  = 60.00
    volume_veh_per_hour = 3600.00
    avg_speed_kmh       = 32.67
    density_percent     = 2.55
    green_seconds       = 43.2
    -> 15m=3836.8 | 2h=1522.8 | 4h=4843.1 veh/hour

  [49/100] siang_cctv_023_20260614_163809.mp4
    vehicle_count_1min  = 134.00
    volume_veh_per_hour = 8040.00
    avg_speed_kmh       = 31.84
    density_percent     = 52.11
    green_seconds       = 68.8
    -> 15m=4645.0 | 2h=1739.3 | 4h=4600.9 veh/hour

  [50/100] siang_cctv_024_20260614_165240.mp4
    vehicle_count_1min  = 42.00
    volume_veh_per_hour = 2520.00
    avg_speed_kmh       = 31.31
    density_percent     = 51.55
    green_seconds       = 71.7
    -> 15m=2864.7 | 2h=1349.1 | 4h=4984.1 veh/hour

  [51/100] siang_cctv_025_20260614_163232.mp4
    vehicle_count_1min  = 15.00
    volume_veh_per_hour = 900.00
    avg_speed_kmh       = 7.13
    density_percent     = 39.68
    green_seconds       = 86.5
    -> 15m=1028.9 | 2h=1509.5 | 4h=3956.7 veh/hour

  [52/100] siang_cctv_026_20260614_163931.mp4
    vehicle_count_1min  = 208.00
    volume_veh_per_hour = 12480.00
    avg_speed_kmh       = 32.27
    density_percent     = 51.21
    green_seconds       = 60.9
    -> 15m=5303.4 | 2h=1709.7 | 4h=4611.7 veh/hour

  [53/100] siang_cctv_027_20260614_165147.mp4
    vehicle_count_1min  = 105.00
    volume_veh_per_hour = 6300.00
    avg_speed_kmh       = 79.08
    density_percent     = 33.16
    green_seconds       = 43.1
    -> 15m=5142.9 | 2h=1570.6 | 4h=4475.4 veh/hour

  [54/100] siang_cctv_028_20260614_165607.mp4
    vehicle_count_1min  = 56.00
    volume_veh_per_hour = 3360.00
    avg_speed_kmh       = 29.79
    density_percent     = 51.41
    green_seconds       = 70.5
    -> 15m=3105.8 | 2h=1683.5 | 4h=4899.1 veh/hour

  [55/100] siang_cctv_029_20260614_164109.mp4
    vehicle_count_1min  = 122.00
    volume_veh_per_hour = 7320.00
    avg_speed_kmh       = 77.64
    density_percent     = 36.40
    green_seconds       = 45.9
    -> 15m=5365.9 | 2h=1588.8 | 4h=4425.0 veh/hour

  [56/100] siang_cctv_030_20260614_165104.mp4
    vehicle_count_1min  = 273.00
    volume_veh_per_hour = 16380.00
    avg_speed_kmh       = 44.33
    density_percent     = 51.76
    green_seconds       = 55.7
    -> 15m=5017.7 | 2h=1722.7 | 4h=4338.8 veh/hour

  [57/100] siang_cctv_031_20260614_165904.mp4
    vehicle_count_1min  = 199.00
    volume_veh_per_hour = 11940.00
    avg_speed_kmh       = 40.45
    density_percent     = 40.55
    green_seconds       = 53.1
    -> 15m=5454.6 | 2h=1713.9 | 4h=4379.1 veh/hour

  [58/100] siang_cctv_032_20260614_165940.mp4
    vehicle_count_1min  = 266.00
    volume_veh_per_hour = 15960.00
    avg_speed_kmh       = 34.57
    density_percent     = 51.56
    green_seconds       = 59.1
    -> 15m=5358.2 | 2h=1722.6 | 4h=4459.6 veh/hour

  [59/100] siang_cctv_033_20260614_164919.mp4
    vehicle_count_1min  = 9.00
    volume_veh_per_hour = 540.00
    avg_speed_kmh       = 6.96
    density_percent     = 15.31
    green_seconds       = 55.2
    -> 15m=1167.7 | 2h=1407.7 | 4h=4140.6 veh/hour

  [60/100] siang_cctv_034_20260614_165211.mp4
    vehicle_count_1min  = 61.00
    volume_veh_per_hour = 3660.00
    avg_speed_kmh       = 28.07
    density_percent     = 13.00
    green_seconds       = 48.8
    -> 15m=3749.8 | 2h=1557.6 | 4h=4903.8 veh/hour

  [61/100] siang_cctv_035_20260614_163500.mp4
    vehicle_count_1min  = 124.00
    volume_veh_per_hour = 7440.00
    avg_speed_kmh       = 31.95
    density_percent     = 9.28
    green_seconds       = 45.4
    -> 15m=5258.6 | 2h=1603.9 | 4h=4259.6 veh/hour

  [62/100] malam_cctv_001_20260518_003725.mp4
    vehicle_count_1min  = 2.00
    volume_veh_per_hour = 120.00
    avg_speed_kmh       = 9.22
    density_percent     = 9.17
    green_seconds       = 51.4
    -> 15m=1053.2 | 2h=1673.4 | 4h=4007.6 veh/hour

  [63/100] malam_cctv_002_20260612_233917.mp4
    vehicle_count_1min  = 12.00
    volume_veh_per_hour = 720.00
    avg_speed_kmh       = 11.41
    density_percent     = 14.94
    green_seconds       = 54.2
    -> 15m=1276.7 | 2h=1461.0 | 4h=4089.7 veh/hour

  [64/100] malam_cctv_003_20260518_004022.mp4
    vehicle_count_1min  = 0.00
    volume_veh_per_hour = 0.00
    avg_speed_kmh       = 80.00
    density_percent     = 0.00
    green_seconds       = 33.0
    -> 15m=207.8 | 2h=165.6 | 4h=247.8 veh/hour

  [65/100] malam_cctv_004_20260613_224239.mp4
    vehicle_count_1min  = 7.00
    volume_veh_per_hour = 420.00
    avg_speed_kmh       = 2.52
    density_percent     = 0.86
    green_seconds       = 48.8
    -> 15m=1258.0 | 2h=1728.3 | 4h=4084.0 veh/hour

  [66/100] malam_cctv_005_20260518_004357.mp4
    vehicle_count_1min  = 56.00
    volume_veh_per_hour = 3360.00
    avg_speed_kmh       = 20.29
    density_percent     = 34.58
    green_seconds       = 70.3
    -> 15m=3012.9 | 2h=1682.1 | 4h=4971.7 veh/hour

  [67/100] malam_cctv_006_20260613_202709.mp4
    vehicle_count_1min  = 4.00
    volume_veh_per_hour = 240.00
    avg_speed_kmh       = 3.72
    density_percent     = 2.29
    green_seconds       = 48.9
    -> 15m=1148.9 | 2h=1686.1 | 4h=3983.8 veh/hour

  [68/100] malam_cctv_007_20260518_033146.mp4
    vehicle_count_1min  = 16.00
    volume_veh_per_hour = 960.00
    avg_speed_kmh       = 17.62
    density_percent     = 14.11
    green_seconds       = 52.7
    -> 15m=1282.0 | 2h=1467.0 | 4h=4257.8 veh/hour

  [69/100] malam_cctv_008_20260518_004504.mp4
    vehicle_count_1min  = 0.00
    volume_veh_per_hour = 0.00
    avg_speed_kmh       = 80.00
    density_percent     = 0.00
    green_seconds       = 33.0
    -> 15m=207.8 | 2h=165.6 | 4h=247.8 veh/hour

  [70/100] malam_cctv_009_20260518_004524.mp4
    vehicle_count_1min  = 0.00
    volume_veh_per_hour = 0.00
    avg_speed_kmh       = 80.00
    density_percent     = 0.00
    green_seconds       = 33.0
    -> 15m=206.9 | 2h=164.5 | 4h=247.6 veh/hour

  [71/100] malam_cctv_010_20260613_202740.mp4
    vehicle_count_1min  = 7.00
    volume_veh_per_hour = 420.00
    avg_speed_kmh       = 6.79
    density_percent     = 1.77
    green_seconds       = 48.2
    -> 15m=1220.0 | 2h=1679.5 | 4h=4046.7 veh/hour

  [72/100] malam_cctv_011_20260613_224301.mp4
    vehicle_count_1min  = 81.00
    volume_veh_per_hour = 4860.00
    avg_speed_kmh       = 22.92
    density_percent     = 57.03
    green_seconds       = 90.0
    -> 15m=2948.4 | 2h=1692.3 | 4h=4859.9 veh/hour

  [73/100] malam_cctv_012_20260613_002431.mp4
    vehicle_count_1min  = 0.00
    volume_veh_per_hour = 0.00
    avg_speed_kmh       = 80.00
    density_percent     = 0.00
    green_seconds       = 33.0
    -> 15m=222.8 | 2h=183.1 | 4h=235.3 veh/hour

  [74/100] malam_cctv_013_20260613_224644.mp4
    vehicle_count_1min  = 6.00
    volume_veh_per_hour = 360.00
    avg_speed_kmh       = 9.01
    density_percent     = 8.59
    green_seconds       = 51.3
    -> 15m=1127.5 | 2h=1668.1 | 4h=4061.3 veh/hour

  [75/100] malam_cctv_014_20260518_033116.mp4
    vehicle_count_1min  = 0.00
    volume_veh_per_hour = 0.00
    avg_speed_kmh       = 80.00
    density_percent     = 0.00
    green_seconds       = 33.0
    -> 15m=205.6 | 2h=162.8 | 4h=247.3 veh/hour

  [76/100] malam_cctv_015_20260613_224732.mp4
    vehicle_count_1min  = 1.00
    volume_veh_per_hour = 60.00
    avg_speed_kmh       = 4.05
    density_percent     = 8.35
    green_seconds       = 52.2
    -> 15m=970.6 | 2h=1672.3 | 4h=3950.9 veh/hour

  [77/100] malam_cctv_016_20260518_033544.mp4
    vehicle_count_1min  = 7.00
    volume_veh_per_hour = 420.00
    avg_speed_kmh       = 9.72
    density_percent     = 27.46
    green_seconds       = 70.3
    -> 15m=1005.4 | 2h=1459.6 | 4h=3838.5 veh/hour

  [78/100] malam_cctv_017_20260613_225035.mp4
    vehicle_count_1min  = 0.00
    volume_veh_per_hour = 0.00

## 13. Save Traffic Feature CSV

In [13]:
df_feat = pd.DataFrame(feature_rows)

feat_csv_path = os.path.join(OUTPUT_DIR, 'traffic_features_lstm.csv')
df_feat.to_csv(feat_csv_path, index=False)
print(f"Saved: {feat_csv_path}")
print(f"Shape: {df_feat.shape}")
df_feat.head()

Saved: /content/outputs/traffic_features_lstm.csv
Shape: (100, 29)

,camera_id,source_video,date,time,period,vehicle_count_1min,volume_veh_per_hour,avg_speed_kmh,queue_length_veh,wait_time_min,...,day,day_of_week,month,is_weekend,hour_sin,hour_cos,weather_condition_Clear,weather_condition_Cloudy,weather_condition_Hot,weather_condition_Rain
0,CAM_002,pagi_cctv_001_20260518_070935.mp4,5/18/2026,6:09:33,Morning Rush,72.0,4320.0,53.62,0.0,0.0,...,15,0,6,0,0.866025,0.5,0.0,1.0,0.0,0.0
1,CAM_001,pagi_cctv_002_20260518_070954.mp4,5/18/2026,6:15:26,Morning Rush,71.0,4260.0,40.17,1.0,0.4,...,15,0,6,0,0.866025,0.5,0.0,1.0,0.0,0.0
2,CAM_001,pagi_cctv_003_20260614_080117.mp4,6/14/2026,8:01:17,Morning Rush,34.0,2040.0,46.51,0.0,0.0,...,15,0,6,0,0.866025,0.5,0.0,1.0,0.0,0.0
3,CAM_011,pagi_cctv_004_20260518_071356.mp4,5/18/2026,6:18:01,Morning Rush,73.0,4380.0,35.38,1.0,0.4,...,15,0,6,0,0.866025,0.5,0.0,1.0,0.0,0.0
4,CAM_007,pagi_cctv_005_20260614_080139.mp4,6/14/2026,8:01:39,Morning Rush,85.0,5100.0,78.82,0.0,0.0,...,15,0,6,0,0.866025,0.5,0.0,1.0,0.0,0.0

## 14. Congestion Level, AI Insight & Recommendation

In [17]:
def get_congestion_level(density_percent, avg_speed_kmh, vehicle_count, queue_length_veh):
    # Normalization
    density = density_percent / 100
    speed = min(avg_speed_kmh, 80)        # cap speed untuk stabilitas model
    speed_norm = speed / 80

    # Non-linear pressure signals
    speed_pressure = (1 - speed_norm) ** 2.0   # semakin lambat -> eksponensial naik
    queue_pressure = min(queue_length_veh / 8, 1)  # bottleneck indicator
    vehicle_pressure = min(vehicle_count / 70, 1)   # kapasitas jalan

    # Base pressure model
    pressure = (
        0.30 * density +
        0.40 * speed_pressure +
        0.20 * queue_pressure +
        0.10 * vehicle_pressure
    )

    # Hard safety rules
    if speed < 1 and density < 0.02:
        return "Low"   # sensor noise / idle condition

    if speed < 5:
        if queue_length_veh >= 2 or density > 0.2:
            return "Severe"  # breakdown traffic
        return "High"       # near-stall condition

    # Synergy effect (real traffic behavior)
    if speed < 20 and density > 0.4:
        pressure += 0.18   # congestion amplification

    if speed < 15 and queue_length_veh > 0:
        pressure += 0.12   # bottleneck effect

    if density > 0.55 and speed < 40:
        pressure += 0.10   # unstable flow region

    # Anti false positive fix
    if speed > 60 and density > 0.5:
        pressure -= 0.12   # fast but dense correction

    if speed < 10:
        pressure += 0.20   # forced congestion detection

    # Contradiction/ Intelligence layer
    if density > 0.45 and speed > 60:
        pressure += 0.20   # unstable fast-dense flow

    if density > 0.5 and queue_length_veh == 0 and speed < 35:
        pressure += 0.10   # hidden congestion detection

    # Final classification
    if pressure >= 0.58:
        return "Severe"
    elif pressure >= 0.44:
        return "High"
    elif pressure >= 0.28:
        return "Medium"
    else:
        return "Low"

# FLOW INTERPRETATION ENGINE
def interpret_flow(density, speed, queue):
    # dense but fast flow (high throughput highway state)
    if density > 0.6 and speed > 45:
        return "dense_fast_flow"

    # congested traffic state
    elif density > 0.55 and speed < 25:
        return "congested_flow"

    # traffic breakdown (near stop)
    elif speed < 8 and queue > 0:
        return "breakdown_flow"

    # unstable transition flow
    elif 0.35 < density < 0.6 and 25 <= speed <= 55:
        return "unstable_flow"

    # free flow condition
    elif density < 0.25 and speed > 50:
        return "free_flow"

    # default normal state
    return "normal_flow"

def build_ai_insight(vc, spd, density, weather, period, queue_len, congestion_level,
                      accident, roadwork, event, green_seconds):
    parts = []

    density_ratio = density / 100
    flow_type = interpret_flow(density_ratio, spd, queue_len)

    if congestion_level == "Severe":
        parts.append(
            f"Severe congestion detected with {queue_len} queued vehicles. "
            f"Speed dropped to {round(spd,1)} km/h indicating traffic breakdown. "
            f"Green duration extended to {green_seconds:.0f}s to help dissipate the queue."
        )

    elif congestion_level == "High":
        if flow_type == "critical_queue_flow":
            parts.append(
                "High congestion caused by queue spillback and bottleneck failure. "
                f"Green duration adjusted to {green_seconds:.0f}s."
            )
        else:
            parts.append(
                f"High traffic density with {queue_len} queued vehicles and speed {round(spd,1)} km/h. "
                f"Green duration adjusted to {green_seconds:.0f}s."
            )

    elif congestion_level == "Medium":
        if flow_type in ["dense_flow", "unstable_flow"]:
            parts.append(
                "Traffic is dense but still maintaining partial flow stability. "
                f"Green duration set to {green_seconds:.0f}s."
            )
        else:
            parts.append(
                f"Moderate congestion with {vc} vehicles and speed {round(spd,1)} km/h. "
                f"Green duration set to {green_seconds:.0f}s."
            )

    else:
        parts.append(
            f"Traffic is stable with low density ({round(density,1)}%) and speed {round(spd,1)} km/h. "
            f"Keep default green duration ({green_seconds:.0f}s)."
        )

    # context layer
    if period in ("Morning Rush", "Evening Rush"):
        parts.append(f"Peak-hour ({period}) increases traffic demand.")

    if weather == "Rain":
        parts.append("Rain may reduce road friction and visibility.")

    if accident > 0:
        parts.append(f"{accident} accident(s) impacting flow.")

    if roadwork:
        parts.append("Roadwork reduces lane capacity.")

    if event:
        parts.append("Nearby event increases traffic volume.")

    return " ".join(parts)

def build_recommendation(congestion, queue, density, speed, green_seconds):
    actions = []

    if congestion == "Severe":
        actions.append(f"Activate emergency traffic control and extend green phase to {green_seconds:.0f}s.")
        if speed < 5:
            actions.append("Deploy rapid incident response team.")
        if queue > 3:
            actions.append("Clear queue buildup immediately.")

    elif congestion == "High":
        actions.append(f"Increase signal optimization; set green duration to {green_seconds:.0f}s.")
        if queue > 5:
            actions.append("Focus on bottleneck queue reduction.")
        if density > 60:
            actions.append("Adjust adaptive signal timing.")

    elif congestion == "Medium":
        actions.append(f"Monitor closely; adjust green duration to {green_seconds:.0f}s if needed.")
        if speed < 30:
            actions.append("Consider pre-emptive signal adjustment.")

    else:
        actions.append(f"Maintain normal operations with default green duration ({green_seconds:.0f}s).")

    return " ".join(actions)

def get_period_label(hour):
    if  5 <= hour <  9: return 'Morning Rush'
    elif 9 <= hour < 16: return 'Daytime'
    elif 16 <= hour < 19: return 'Evening Rush'
    elif 19 <= hour < 23: return 'Night'
    else:                 return 'Late Night'

# MAIN PIPELINE — gabungkan congestion, insight, recommendation, dan hasil LSTM
prediction_records = []

for idx, row in vc_df.iterrows():
    vc      = int(row['vehicle_count'])
    spd     = float(row['avg_speed_kmh'])
    density = float(row['density_percent'])
    queue   = int(row['queue_length_veh'])
    weather = str(row['weather'])
    green_sec = float(row['green_seconds'])

    # Clean the time string by removing ' AM' or ' PM' if present
    time_str = str(row['time'])
    if ' AM' in time_str:
        time_str = time_str.replace(' AM', '')
    elif ' PM' in time_str:
        time_str = time_str.replace(' PM', '')

    dt_obj = datetime.strptime(f"{row['date']} {time_str}", '%m/%d/%Y %H:%M:%S')
    hour   = dt_obj.hour
    period = row.get('period', get_period_label(hour))

    cong = get_congestion_level(density, spd, vc, queue)

    insight = build_ai_insight(
        vc, spd, density, weather, period, queue, cong,
        int(row.get('accident_count', 0)),
        int(row.get('roadwork_flag', 0)),
        int(row.get('event_flag', 0)),
        green_sec
    )
    recom = build_recommendation(cong, queue, density, spd, green_sec)

    rec = {
        "camera_id":    row.get('camera_id', f'CAM_{idx+1:03d}'),
        "source_video": row.get('source_video', ''),

        # TIME INFO
        "date":   str(row['date']),
        "time":   str(row['time']),
        "period": period,

        # LOCATION INFO
        "latitude":  row.get('latitude'),
        "longitude": row.get('longitude'),

        # WEATHER INFO
        "weather":        weather,
        "weather_temp_c": float(row['weather_temp_c']),

        # TRAFFIC CORE (dari hasil YOLO)
        "vehicle_count":       vc,
        "vehicle_count_1min":  int(row['vehicle_count_1min']),
        "volume_veh_per_hour": int(row['volume_veh_per_hour']),
        "avg_speed_kmh":       round(spd, 2),
        "density_percent":     round(density, 2),
        "queue_length_veh":    queue,
        "green_seconds":       round(green_sec, 1),
        "congestion_level":    cong,

        # MODEL OUTPUT (LSTM)
        "predicted_volume_15m": float(row['predicted_volume_15m']),
        "predicted_volume_2h":  float(row['predicted_volume_2h']),
        "predicted_volume_4h":  float(row['predicted_volume_4h']),

        "model_mape_15m": HORIZON_MAPE['15m'],
        "model_mape_2h":  HORIZON_MAPE['2h'],
        "model_mape_4h":  HORIZON_MAPE['4h'],

        # METADATA
        "ai_insight":     insight,
        "recommendation": recom,
    }
    prediction_records.append(rec)

print(f"Records built: {len(prediction_records)}")
for rec in prediction_records:
    print(
        rec['camera_id'], rec['source_video'],
        "| pred_15m =", rec['predicted_volume_15m'],
        "| pred_2h ="  , rec['predicted_volume_2h'],
        "| pred_4h ="  , rec['predicted_volume_4h'],
        "| green ="    , rec['green_seconds'],
        "| cong ="     , rec['congestion_level']
    )

Records built: 100
CAM_002 pagi_cctv_001_20260518_070935.mp4 | pred_15m = 4506.75 | pred_2h = 1585.76 | pred_4h = 4978.05 | green = 44.2 | cong = Low
CAM_001 pagi_cctv_002_20260518_070954.mp4 | pred_15m = 3870.67 | pred_2h = 1627.97 | pred_4h = 4986.5 | green = 57.8 | cong = Medium
CAM_001 pagi_cctv_003_20260614_080117.mp4 | pred_15m = 1750.73 | pred_2h = 1215.82 | pred_4h = 4722.32 | green = 42.0 | cong = Low
CAM_011 pagi_cctv_004_20260518_071356.mp4 | pred_15m = 3832.92 | pred_2h = 1632.3 | pred_4h = 5003.04 | green = 58.8 | cong = Medium
CAM_007 pagi_cctv_005_20260614_080139.mp4 | pred_15m = 4123.86 | pred_2h = 1507.94 | pred_4h = 4727.08 | green = 46.9 | cong = Medium
CAM_006 pagi_cctv_006_20260518_071450.mp4 | pred_15m = 3183.62 | pred_2h = 1678.69 | pred_4h = 4930.19 | green = 90.0 | cong = Severe
CAM_009 pagi_cctv_007_20260614_080221.mp4 | pred_15m = 4035.83 | pred_2h = 1624.52 | pred_4h = 4751.33 | green = 57.9 | cong = Medium
CAM_011 pagi_cctv_008_20260614_083937.mp4 | pred_15m = 3503.32 | pred_2h = 1480.01 | pred_4h = 4737.87 | green = 53.2 | cong = Medium
CAM_004 pagi_cctv_009_20260518_071625.mp4 | pred_15m = 5143.07 | pred_2h = 1825.16 | pred_4h = 4752.02 | green = 44.6 | cong = Low
CAM_005 pagi_cctv_010_20260614_084252.mp4 | pred_15m = 214.85 | pred_2h = 175.56 | pred_4h = 252.97 | green = 33.0 | cong = Low
CAM_005 pagi_cctv_011_20260614_090616.mp4 | pred_15m = 214.85 | pred_2h = 175.56 | pred_4h = 252.97 | green = 33.0 | cong = Low
CAM_011 pagi_cctv_012_20260614_090310.mp4 | pred_15m = 3431.16 | pred_2h = 1475.47 | pred_4h = 4677.03 | green = 53.9 | cong = Medium
CAM_012 pagi_cctv_013_20260614_081117.mp4 | pred_15m = 3651.49 | pred_2h = 1523.95 | pred_4h = 4474.6 | green = 54.2 | cong = Medium
CAM_007 pagi_cctv_014_20260518_072255.mp4 | pred_15m = 5038.54 | pred_2h = 1800.54 | pred_4h = 4425.06 | green = 55.9 | cong = Medium
CAM_008 pagi_cctv_015_20260518_072703.mp4 | pred_15m = 1456.7 | pred_2h = 1452.75 | pred_4h = 4424.59 | green = 90.0 | cong = Severe
CAM_004 pagi_cctv_016_20260614_084327.mp4 | pred_15m = 3190.85 | pred_2h = 1704.69 | pred_4h = 4768.38 | green = 41.4 | cong = Low
CAM_002 pagi_cctv_017_20260614_090631.mp4 | pred_15m = 3395.65 | pred_2h = 1467.24 | pred_4h = 4897.16 | green = 51.1 | cong = Medium
CAM_001 pagi_cctv_018_20260614_090735.mp4 | pred_15m = 422.7 | pred_2h = 1150.55 | pred_4h = 3982.82 | green = 40.7 | cong = Low
CAM_012 pagi_cctv_019_20260614_080343.mp4 | pred_15m = 3252.89 | pred_2h = 1310.0 | pred_4h = 4580.49 | green = 48.6 | cong = Medium
CAM_003 pagi_cctv_020_20260614_084403.mp4 | pred_15m = 3944.53 | pred_2h = 1955.03 | pred_4h = 4289.9 | green = 33.8 | cong = Low
CAM_009 pagi_cctv_021_20260614_090559.mp4 | pred_15m = 5472.48 | pred_2h = 1811.94 | pred_4h = 4647.27 | green = 47.7 | cong = Low
CAM_004 pagi_cctv_022_20260614_090032.mp4 | pred_15m = 3423.46 | pred_2h = 1350.9 | pred_4h = 4656.8 | green = 47.7 | cong = Medium
CAM_007 pagi_cctv_023_20260614_090010.mp4 | pred_15m = 1006.29 | pred_2h = 1936.73 | pred_4h = 4151.12 | green = 37.5 | cong = Low
CAM_012 pagi_cctv_024_20260614_083635.mp4 | pred_15m = 2841.9 | pred_2h = 1454.04 | pred_4h = 4632.91 | green = 59.7 | cong = High
CAM_010 pagi_cctv_025_20260614_085807.mp4 | pred_15m = 4592.45 | pred_2h = 1805.24 | pred_4h = 4628.4 | green = 65.6 | cong = High
CAM_002 pagi_cctv_026_20260614_083559.mp4 | pred_15m = 3525.39 | pred_2h = 1437.94 | pred_4h = 4966.55 | green = 45.7 | cong = Low
CAM_008 pagi_cctv_027_20260614_085504.mp4 | pred_15m = 5320.77 | pred_2h = 1896.36 | pred_4h = 4448.5 | green = 58.4 | cong = Medium
CAM_007 pagi_cctv_028_20260614_083354.mp4 | pred_15m = 3790.35 | pred_2h = 1447.11 | pred_4h = 4674.97 | green = 48.3 | cong = Medium
CAM_010 siang_cctv_001_20260518_163906.mp4 | pred_15m = 3571.9 | pred_2h = 1661.15 | pred_4h = 4752.91 | green = 63.9 | cong = High
CAM_010 siang_cctv_002_20260614_163126.mp4 | pred_15m = 5294.05 | pred_2h = 1719.54 | pred_4h = 4577.73 | green = 59.0 | cong = Medium
CAM_003 siang_cctv_003_20260518_165921.mp4 | pred_15m = 970.56 | pred_2h = 1474.76 | pred_4h = 3790.76 | green = 70.6 | cong = Severe
CAM_005 siang_cctv_004_20260518_170659.mp4 | pred_15m = 4965.44 | pred_2h = 1714.93 | pred_4h = 4722.17 | green = 60.3 | cong = High
CAM_011 siang_cctv_005_20260518_171425.mp4 | pred_15m = 4073.9 | pred_2h = 1784.67 | pred_4h = 4665.11 | green = 90.0 | cong = Severe
CAM_003 siang_cctv_006_20260614_170915.mp4 | pred_15m = 5172.76 | pred_2h = 1765.07 | pred_4h = 4565.29 | green = 68.9 | cong = High
CAM_011 siang_cctv_007_20260518_160452.mp4 | pred_15m = 4723.02 | pred_2h = 1949.57 | pred_4h = 4657.33 | green = 55.6 | cong = Medium
CAM_011 siang_cctv_008_20260518_151934.mp4 | pred_15m = 5072.38 | pred_2h = 1633.66 | pred_4h = 4553.98 | green = 38.9 | cong = Low
CAM_004 siang_cctv_009_20260614_170730.mp4 | pred_15m = 5385.18 | pred_2h = 1807.35 | pred_4h = 4415.88 | green = 52.7 | cong = Medium
CAM_012 siang_cctv_010_20260614_171050.mp4 | pred_15m = 4064.4 | pred_2h = 1739.05 | pred_4h = 4540.67 | green = 62.4 | cong = High
CAM_005 siang_cctv_011_20260614_171352.mp4 | pred_15m = 1180.29 | pred_2h = 1591.7 | pred_4h = 4011.57 | green = 49.1 | cong = High
CAM_007 siang_cctv_012_20260614_165224.mp4 | pred_15m = 4883.8 | pred_2h = 1692.94 | pred_4h = 4432.07 | green = 48.0 | cong = Low
CAM_008 siang_cctv_013_20260614_171437.mp4 | pred_15m = 5098.77 | pred_2h = 1728.51 | pred_4h = 4196.71 | green = 56.8 | cong = Medium
CAM_001 siang_cctv_016_20260614_171739.mp4 | pred_15m = 3235.97 | pred_2h = 1909.72 | pred_4h = 4171.38 | green = 34.2 | cong = Low
CAM_009 siang_cctv_017_20260614_171746.mp4 | pred_15m = 5385.9 | pred_2h = 1718.32 | pred_4h = 4498.91 | green = 58.4 | cong = Medium
CAM_011 siang_cctv_018_20260614_171903.mp4 | pred_15m = 3022.37 | pred_2h = 1375.15 | pred_4h = 5000.9 | green = 52.7 | cong = Medium
CAM_002 siang_cctv_019_20260614_172002.mp4 | pred_15m = 3075.72 | pred_2h = 1732.93 | pred_4h = 5026.48 | green = 90.0 | cong = Severe
CAM_003 siang_cctv_020_20260614_165923.mp4 | pred_15m = 5400.84 | pred_2h = 1716.96 | pred_4h = 4408.25 | green = 58.7 | cong = Medium
CAM_003 siang_cctv_021_20260614_163509.mp4 | pred_15m = 5268.15 | pred_2h = 1860.36 | pred_4h = 4394.98 | green = 57.5 | cong = High
CAM_011 siang_cctv_022_20260614_163451.mp4 | pred_15m = 3836.76 | pred_2h = 1522.83 | pred_4h = 4843.06 | green = 43.2 | cong = Low
CAM_007 siang_cctv_023_20260614_163809.mp4 | pred_15m = 4644.98 | pred_2h = 1739.27 | pred_4h = 4600.92 | green = 68.8 | cong = High
CAM_001 siang_cctv_024_20260614_165240.mp4 | pred_15m = 2864.7 | pred_2h = 1349.06 | pred_4h = 4984.08 | green = 71.7 | cong = Severe
CAM_005 siang_cctv_025_20260614_163232.mp4 | pred_15m = 1028.93 | pred_2h = 1509.47 | pred_4h = 3956.68 | green = 86.5 | cong = Severe
CAM_009 siang_cctv_026_20260614_163931.mp4 | pred_15m = 5303.41 | pred_2h = 1709.68 | pred_4h = 4611.66 | green = 60.9 | cong = High
CAM_004 siang_cctv_027_20260614_165147.mp4 | pred_15m = 5142.92 | pred_2h = 1570.62 | pred_4h = 4475.38 | green = 43.1 | cong = Low
CAM_011 siang_cctv_028_20260614_165607.mp4 | pred_15m = 3105.83 | pred_2h = 1683.55 | pred_4h = 4899.1 | green = 70.5 | cong = Severe
CAM_012 siang_cctv_029_20260614_164109.mp4 | pred_15m = 5365.86 | pred_2h = 1588.75 | pred_4h = 4425.0 | green = 45.9 | cong = Low
CAM_008 siang_cctv_030_20260614_165104.mp4 | pred_15m = 5017.66 | pred_2h = 1722.74 | pred_4h = 4338.8 | green = 55.7 | cong = Medium
CAM_009 siang_cctv_031_20260614_165904.mp4 | pred_15m = 5454.65 | pred_2h = 1713.88 | pred_4h = 4379.06 | green = 53.1 | cong = Medium
CAM_010 siang_cctv_032_20260614_165940.mp4 | pred_15m = 5358.18 | pred_2h = 1722.56 | pred_4h = 4459.61 | green = 59.1 | cong = Medium
CAM_005 siang_cctv_033_20260614_164919.mp4 | pred_15m = 1167.69 | pred_2h = 1407.65 | pred_4h = 4140.57 | green = 55.2 | cong = Severe
CAM_002 siang_cctv_034_20260614_165211.mp4 | pred_15m = 3749.75 | pred_2h = 1557.6 | pred_4h = 4903.76 | green = 48.8 | cong = Low
CAM_001 siang_cctv_035_20260614_163500.mp4 | pred_15m = 5258.64 | pred_2h = 1603.92 | pred_4h = 4259.55 | green = 45.4 | cong = Low
CAM_001 malam_cctv_001_20260518_003725.mp4 | pred_15m = 1053.15 | pred_2h = 1673.37 | pred_4h = 4007.56 | green = 51.4 | cong = Severe
CAM_009 malam_cctv_002_20260612_233917.mp4 | pred_15m = 1276.72 | pred_2h = 1460.98 | pred_4h = 4089.73 | green = 54.2 | cong = High
CAM_004 malam_cctv_003_20260518_004022.mp4 | pred_15m = 207.78 | pred_2h = 165.62 | pred_4h = 247.78 | green = 33.0 | cong = Low
CAM_005 malam_cctv_004_20260613_224239.mp4 | pred_15m = 1257.96 | pred_2h = 1728.29 | pred_4h = 4083.98 | green = 48.8 | cong = High
CAM_005 malam_cctv_005_20260518_004357.mp4 | pred_15m = 3012.93 | pred_2h = 1682.11 | pred_4h = 4971.71 | green = 70.3 | cong = High
CAM_002 malam_cctv_006_20260613_202709.mp4 | pred_15m = 1148.88 | pred_2h = 1686.07 | pred_4h = 3983.85 | green = 48.9 | cong = High
CAM_007 malam_cctv_007_20260518_033146.mp4 | pred_15m = 1281.98 | pred_2h = 1467.0 | pred_4h = 4257.81 | green = 52.7 | cong = Medium
CAM_011 malam_cctv_008_20260518_004504.mp4 | pred_15m = 207.78 | pred_2h = 165.62 | pred_4h = 247.78 | green = 33.0 | cong = Low
CAM_003 malam_cctv_009_20260518_004524.mp4 | pred_15m = 206.86 | pred_2h = 164.48 | pred_4h = 247.58 | green = 33.0 | cong = Low
CAM_011 malam_cctv_010_20260613_202740.mp4 | pred_15m = 1220.02 | pred_2h = 1679.49 | pred_4h = 4046.68 | green = 48.2 | cong = High
CAM_008 malam_cctv_011_20260613_224301.mp4 | pred_15m = 2948.41 | pred_2h = 1692.3 | pred_4h = 4859.91 | green = 90.0 | cong = Severe
CAM_001 malam_cctv_012_20260613_002431.mp4 | pred_15m = 222.83 | pred_2h = 183.08 | pred_4h = 235.26 | green = 33.0 | cong = Low
CAM_012 malam_cctv_013_20260613_224644.mp4 | pred_15m = 1127.49 | pred_2h = 1668.12 | pred_4h = 4061.31 | green = 51.3 | cong = Severe
CAM_011 malam_cctv_014_20260518_033116.mp4 | pred_15m = 205.56 | pred_2h = 162.83 | pred_4h = 247.28 | green = 33.0 | cong = Low
CAM_002 malam_cctv_015_20260613_224732.mp4 | pred_15m = 970.56 | pred_2h = 1672.34 | pred_4h = 3950.89 | green = 52.2 | cong = High
CAM_005 malam_cctv_016_20260518_033544.mp4 | pred_15m = 1005.43 | pred_2h = 1459.64 | pred_4h = 3838.5 | green = 70.3 | cong = Severe
CAM_003 malam_cctv_017_20260613_225035.mp4 | pred_15m = 1121.99 | pred_2h = 1708.91 | pred_4h = 3884.32 | green = 48.6 | cong = High
CAM_010 malam_cctv_018_20260613_225338.mp4 | pred_15m = 2510.51 | pred_2h = 1563.92 | pred_4h = 4847.19 | green = 69.7 | cong = High
CAM_011 malam_cctv_019_20260613_225426.mp4 | pred_15m = 1472.36 | pred_2h = 1697.74 | pred_4h = 4302.47 | green = 48.0 | cong = High
CAM_010 malam_cctv_020_20260612_234058.mp4 | pred_15m = 1514.7 | pred_2h = 1535.77 | pred_4h = 4111.1 | green = 51.7 | cong = Severe
CAM_004 malam_cctv_0221_20260613_002132.mp4 | pred_15m = 207.31 | pred_2h = 165.04 | pred_4h = 247.68 | green = 33.0 | cong = Low
CAM_012 malam_cctv_022_20260613_202805.mp4 | pred_15m = 1229.41 | pred_2h = 1676.19 | pred_4h = 4044.95 | green = 47.9 | cong = High
CAM_007 malam_cctv_023_20260613_224005.mp4 | pred_15m = 211.12 | pred_2h = 169.47 | pred_4h = 248.4 | green = 33.0 | cong = Low
CAM_012 malam_cctv_024_20260612_234033.mp4 | pred_15m = 1102.77 | pred_2h = 1703.75 | pred_4h = 3965.82 | green = 47.9 | cong = High
CAM_001 malam_cctv_025_20260612_234118.mp4 | pred_15m = 1022.35 | pred_2h = 1704.08 | pred_4h = 3892.51 | green = 47.8 | cong = High
CAM_004 malam_cctv_026_20260613_224453.mp4 | pred_15m = 217.93 | pred_2h = 168.4 | pred_4h = 245.14 | green = 33.2 | cong = Low
CAM_005 malam_cctv_027_20260612_234423.mp4 | pred_15m = 844.23 | pred_2h = 1359.24 | pred_4h = 3957.59 | green = 44.0 | cong = Low
CAM_002 malam_cctv_028_20260613_001645.mp4 | pred_15m = 1155.79 | pred_2h = 1671.78 | pred_4h = 4082.7 | green = 52.3 | cong = High
CAM_003 malam_cctv_029_20260613_202829.mp4 | pred_15m = 1082.16 | pred_2h = 1659.44 | pred_4h = 3890.55 | green = 48.8 | cong = High
CAM_002 malam_cctv_030_20260612_234529.mp4 | pred_15m = 949.28 | pred_2h = 1465.8 | pred_4h = 3946.88 | green = 57.6 | cong = Severe
CAM_010 malam_cctv_031_20260613_001733.mp4 | pred_15m = 1102.56 | pred_2h = 1315.85 | pred_4h = 3785.53 | green = 79.5 | cong = Severe
CAM_001 malam_cctv_032_20260613_203129.mp4 | pred_15m = 729.75 | pred_2h = 1331.83 | pred_4h = 3860.77 | green = 60.2 | cong = High
CAM_004 malam_cctv_033_20260612_234049.mp4 | pred_15m = 226.57 | pred_2h = 180.07 | pred_4h = 249.29 | green = 33.0 | cong = Low
CAM_007 malam_cctv_034_20260612_234828.mp4 | pred_15m = 951.9 | pred_2h = 1627.86 | pred_4h = 3974.53 | green = 51.6 | cong = Severe
CAM_009 malam_cctv_035_20260613_203432.mp4 | pred_15m = 1020.87 | pred_2h = 1469.47 | pred_4h = 3965.38 | green = 77.5 | cong = Severe
CAM_008 malam_cctv_036_20260613_002013.mp4 | pred_15m = 2836.34 | pred_2h = 1662.72 | pred_4h = 4757.51 | green = 90.0 | cong = Severe
CAM_003 malam_cctv_037_20260612_235125.mp4 | pred_15m = 1010.42 | pred_2h = 1694.28 | pred_4h = 3913.91 | green = 48.8 | cong = High
CAM_010 malam_cctv_038_20260613_202601.mp4 | pred_15m = 2416.37 | pred_2h = 1474.99 | pred_4h = 4630.02 | green = 58.0 | cong = Medium
CAM_008 malam_cctv_039_20260613_203737.mp4 | pred_15m = 3719.79 | pred_2h = 1650.01 | pred_4h = 4834.97 | green = 72.5 | cong = Severe

## 15. Save Prediction Output (CSV & JSON)

In [18]:
json_path = os.path.join(OUTPUT_DIR, 'lstm_prediction_output.json')
with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(prediction_records, f, ensure_ascii=False, indent=2)
print(f"Saved: {json_path}")

pred_df  = pd.DataFrame(prediction_records)
pred_csv = os.path.join(OUTPUT_DIR, 'lstm_prediction_output.csv')
pred_df.to_csv(pred_csv, index=False)
print(f"Saved: {pred_csv}")

Saved: /content/outputs/lstm_prediction_output.json
Saved: /content/outputs/lstm_prediction_output.csv

## 16. Prediction Validation & Distribution Analysis (15m / 2h / 4h)

In [19]:
print("=== LSTM PREDICTION VALIDATION (15m / 2h / 4h) ===")

vehicle_counts = np.array([rec['vehicle_count'] for rec in prediction_records])
horizon_stats = {}

for h in ['15m', '2h', '4h']:
    preds  = np.array([rec[f'predicted_volume_{h}'] for rec in prediction_records])
    mape_h = HORIZON_MAPE.get(h)

    pred_min, pred_max   = float(np.min(preds)), float(np.max(preds))
    pred_mean, pred_std  = float(np.mean(preds)), float(np.std(preds))
    pred_spread          = pred_max - pred_min
    relative_spread      = pred_spread / max(pred_mean, 1)

    corr_value = None
    if len(np.unique(vehicle_counts)) > 1:
        corr_value = float(np.corrcoef(vehicle_counts, preds)[0, 1])

    print(f"\n--- Horizon {h} ---")
    print(f"  Model MAPE       : {mape_h}")
    print(f"  Min Prediction   : {pred_min:.2f}")
    print(f"  Max Prediction   : {pred_max:.2f}")
    print(f"  Mean Prediction  : {pred_mean:.2f}")
    print(f"  Std Deviation    : {pred_std:.2f}")
    print(f"  Prediction Spread: {pred_spread:.2f}")
    print(f"  Relative Spread  : {relative_spread:.2%}")

    if relative_spread < 0.10:
        print("  [WARNING] Predictions are highly concentrated.")
    elif relative_spread < 0.20:
        print("  [INFO] Predictions show moderate variability.")
    else:
        print("  [OK] Predictions show strong variability.")

    if corr_value is not None:
        print(f"  Correlation w/ vehicle_count: {corr_value:.3f}")
        if abs(corr_value) < 0.20:
            print("  [WARNING] Weak relationship with vehicle_count.")
        elif abs(corr_value) < 0.50:
            print("  [INFO] Moderate relationship with vehicle_count.")
        else:
            print("  [OK] Strong relationship with vehicle_count.")
    else:
        print("  [INFO] Correlation undefined (no variance in vehicle_count)")

    # Confidence range per record (jika MAPE tersedia)
    if mape_h is not None:
        for rec, p in zip(prediction_records, preds):
            lower = p * (1 - mape_h / 100)
            upper = p * (1 + mape_h / 100)
            rec[f'confidence_range_{h}'] = {
                "lower_bound": float(lower),
                "upper_bound": float(upper),
            }
    else:
        for rec in prediction_records:
            rec[f'confidence_range_{h}'] = None

    horizon_stats[h] = {
        "model_mape": mape_h,
        "min_prediction": pred_min,
        "max_prediction": pred_max,
        "mean_prediction": pred_mean,
        "std_deviation": pred_std,
        "prediction_spread": pred_spread,
        "relative_spread_percent": relative_spread * 100,
        "correlation_vehicle_count_prediction": corr_value,
        "analysis": {
            "prediction_variability": (
                "Low" if relative_spread < 0.10 else
                "Moderate" if relative_spread < 0.20 else
                "High"
            ),
            "output_collapse_detected": bool(relative_spread < 0.02),
            "correlation_strength": (
                "Undefined" if corr_value is None else
                "Weak" if abs(corr_value) < 0.20 else
                "Moderate" if abs(corr_value) < 0.50 else
                "Strong"
            ),
        }
    }

=== LSTM PREDICTION VALIDATION (15m / 2h / 4h) ===

--- Horizon 15m ---
  Model MAPE       : 21.8059
  Min Prediction   : 205.56
  Max Prediction   : 5472.48
  Mean Prediction  : 2752.94
  Std Deviation    : 1795.50
  Prediction Spread: 5266.92
  Relative Spread  : 191.32%
  [OK] Predictions show strong variability.
  Correlation w/ vehicle_count: 0.542
  [OK] Strong relationship with vehicle_count.

--- Horizon 2h ---
  Model MAPE       : 27.035
  Min Prediction   : 162.83
  Max Prediction   : 1955.03
  Mean Prediction  : 1458.56
  Std Deviation    : 478.41
  Prediction Spread: 1792.20
  Relative Spread  : 122.87%
  [OK] Predictions show strong variability.
  Correlation w/ vehicle_count: 0.299
  [INFO] Moderate relationship with vehicle_count.

--- Horizon 4h ---
  Model MAPE       : 32.492
  Min Prediction   : 235.26
  Max Prediction   : 5026.48
  Mean Prediction  : 3970.98
  Std Deviation    : 1353.49
  Prediction Spread: 4791.22
  Relative Spread  : 120.66%
  [OK] Predictions show strong variability.
  Correlation w/ vehicle_count: 0.272
  [INFO] Moderate relationship with vehicle_count.

## 17. Save Inference Summary JSON

In [20]:
summary = {
    "total_rows_processed": len(prediction_records),

    "seq_len_used":  SEQ_LEN,
    "feature_count": NUM_FEATURES,
    "horizons":      ['15m', '2h', '4h'],
    "horizon_mape":  HORIZON_MAPE,

    "horizon_stats": horizon_stats,

    "predictions": prediction_records,
}

summary_path = os.path.join(OUTPUT_DIR, "lstm_inference_summary.json")
with open(summary_path, "w", encoding="utf-8") as f:
    json.dump(summary, f, indent=2, ensure_ascii=False)

print(f"Saved: {summary_path}")

Saved: /content/outputs/lstm_inference_summary.json

## 18. Zip Outputs and Download

In [21]:
import shutil
zip_path = '/content/traffix_lstm_inference_outputs'
shutil.make_archive(zip_path, 'zip', OUTPUT_DIR)
print(f"Created: {zip_path}.zip")

from google.colab import files
files.download(f"{zip_path}.zip")

Created: /content/traffix_lstm_inference_outputs.zip

## 19. Final Summary

In [22]:
print("\n=== LSTM INFERENCE COMPLETE ===")
print(f"  Rows processed : {len(prediction_records)}")
print(f"  MAPE 15m       : {HORIZON_MAPE['15m']}")
print(f"  MAPE 2h        : {HORIZON_MAPE['2h']}")
print(f"  MAPE 4h        : {HORIZON_MAPE['4h']}")
print()
for r in prediction_records:
    print(f"  {r['camera_id']} | {r['source_video']}")
    print(f"    {r['date']} {r['time']} | {r['period']}")
    if r['latitude']:
        print(f"    lat={r['latitude']}  lon={r['longitude']}")
    print(f"    weather={r['weather']} {r['weather_temp_c']}C")
    print(f"    vc={r['vehicle_count']} veh | vol={r['volume_veh_per_hour']} veh/hr | congestion={r['congestion_level']}")
    print(f"    green_seconds={r['green_seconds']}s")
    print(f"    predicted_volume -> 15m={r['predicted_volume_15m']} | 2h={r['predicted_volume_2h']} | 4h={r['predicted_volume_4h']}")
    print(f"    {r['ai_insight']}")
    print(f"    -> {r['recommendation']}")
    print()

=== LSTM INFERENCE COMPLETE ===
  Rows processed : 100
  MAPE 15m       : 21.8059
  MAPE 2h        : 27.035
  MAPE 4h        : 32.492

  CAM_002 | pagi_cctv_001_20260518_070935.mp4
    5/18/2026 6:09:33 | Morning Rush
    lat=-6.2131428  lon=106.6837664
    weather=Cloudy 25.6C
    vc=23 veh | vol=4320 veh/hr | congestion=Low
    green_seconds=44.2s
    predicted_volume -> 15m=4506.75 | 2h=1585.76 | 4h=4978.05
    Traffic is stable with low density (19.8%) and speed 53.6 km/h. Keep default green duration (44s). Peak-hour (Morning Rush) increases traffic demand.
    -> Maintain normal operations with default green duration (44s).

  CAM_001 | pagi_cctv_002_20260518_070954.mp4
    5/18/2026 6:15:26 | Morning Rush
    lat=-6.1911513  lon=106.7441887
    weather=Cloudy 26.8C
    vc=67 veh | vol=4260 veh/hr | congestion=Medium
    green_seconds=57.8s
    predicted_volume -> 15m=3870.67 | 2h=1627.97 | 4h=4986.5
    Traffic is dense but still maintaining partial flow stability. Green duration set to 58s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 58s if needed.

  CAM_001 | pagi_cctv_003_20260614_080117.mp4
    6/14/2026 8:01:17 | Morning Rush
    lat=-6.1911513  lon=106.744189
    weather=Cloudy 27.8C
    vc=9 veh | vol=2040 veh/hr | congestion=Low
    green_seconds=42.0s
    predicted_volume -> 15m=1750.73 | 2h=1215.82 | 4h=4722.32
    Traffic is stable with low density (7.6%) and speed 46.5 km/h. Keep default green duration (42s). Peak-hour (Morning Rush) increases traffic demand.
    -> Maintain normal operations with default green duration (42s).

  CAM_011 | pagi_cctv_004_20260518_071356.mp4
    5/18/2026 6:18:01 | Morning Rush
    lat=-6.191635  lon=106.730124
    weather=Cloudy 25.6C
    vc=63 veh | vol=4380 veh/hr | congestion=Medium
    green_seconds=58.8s
    predicted_volume -> 15m=3832.92 | 2h=1632.3 | 4h=5003.04
    Traffic is dense but still maintaining partial flow stability. Green duration set to 59s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 59s if needed.

  CAM_007 | pagi_cctv_005_20260614_080139.mp4
    6/14/2026 8:01:39 | Morning Rush
    lat=-6.2024517  lon=106.705216
    weather=Cloudy 27.8C
    vc=54 veh | vol=5100 veh/hr | congestion=Medium
    green_seconds=46.9s
    predicted_volume -> 15m=4123.86 | 2h=1507.94 | 4h=4727.08
    Moderate congestion with 54 vehicles and speed 78.8 km/h. Green duration set to 47s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 47s if needed.

  CAM_006 | pagi_cctv_006_20260518_071450.mp4
    5/18/2026 6:20:24 | Morning Rush
    lat=-6.2265884  lon=106.6163871
    weather=Cloudy 25.2C
    vc=93 veh | vol=5400 veh/hr | congestion=Severe
    green_seconds=90.0s
    predicted_volume -> 15m=3183.62 | 2h=1678.69 | 4h=4930.19
    Severe congestion detected with 28 queued vehicles. Speed dropped to 20.5 km/h indicating traffic breakdown. Green duration extended to 90s to help dissipate the queue. Peak-hour (Morning Rush) increases traffic demand.
    -> Activate emergency traffic control and extend green phase to 90s. Clear queue buildup immediately.

  CAM_009 | pagi_cctv_007_20260614_080221.mp4
    6/14/2026 8:02:21 | Morning Rush
    lat=-6.226591  lon=106.616335
    weather=Cloudy 28.1C
    vc=66 veh | vol=4980 veh/hr | congestion=Medium
    green_seconds=57.9s
    predicted_volume -> 15m=4035.83 | 2h=1624.52 | 4h=4751.33
    Traffic is dense but still maintaining partial flow stability. Green duration set to 58s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 58s if needed.

  CAM_011 | pagi_cctv_008_20260614_083937.mp4
    6/14/2026 8:39:37 | Morning Rush
    lat=-6.223507  lon=106.623837
    weather=Cloudy 28.9C
    vc=239 veh | vol=4800 veh/hr | congestion=Medium
    green_seconds=53.2s
    predicted_volume -> 15m=3503.32 | 2h=1480.01 | 4h=4737.87
    Moderate congestion with 239 vehicles and speed 70.6 km/h. Green duration set to 53s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 53s if needed.

  CAM_004 | pagi_cctv_009_20260518_071625.mp4
    5/18/2026 6:20:49 | Morning Rush
    lat=-6.2024517  lon=106.7052155
    weather=Cloudy 25.6C
    vc=23 veh | vol=5940 veh/hr | congestion=Low
    green_seconds=44.6s
    predicted_volume -> 15m=5143.07 | 2h=1825.16 | 4h=4752.02
    Traffic is stable with low density (20.0%) and speed 52.2 km/h. Keep default green duration (45s). Peak-hour (Morning Rush) increases traffic demand.
    -> Maintain normal operations with default green duration (45s).

  CAM_005 | pagi_cctv_010_20260614_084252.mp4
    6/14/2026 8:42:52 | Morning Rush
    lat=-6.2225065  lon=106.639475
    weather=Cloudy 28.9C
    vc=0 veh | vol=0 veh/hr | congestion=Low
    green_seconds=33.0s
    predicted_volume -> 15m=214.85 | 2h=175.56 | 4h=252.97
    Traffic is stable with low density (0.0%) and speed 80.0 km/h. Keep default green duration (33s). Peak-hour (Morning Rush) increases traffic demand.
    -> Maintain normal operations with default green duration (33s).

  CAM_005 | pagi_cctv_011_20260614_090616.mp4
    6/14/2026 9:06:16 | Daytime
    lat=-6.2225065  lon=106.639475
    weather=Cloudy 28.9C
    vc=0 veh | vol=0 veh/hr | congestion=Low
    green_seconds=33.0s
    predicted_volume -> 15m=214.85 | 2h=175.56 | 4h=252.97
    Traffic is stable with low density (0.0%) and speed 80.0 km/h. Keep default green duration (33s).
    -> Maintain normal operations with default green duration (33s).

  CAM_011 | pagi_cctv_012_20260614_090310.mp4
    6/14/2026 9:03:10 | Daytime
    lat=-6.223507  lon=106.623837
    weather=Cloudy 28.9C
    vc=229 veh | vol=5040 veh/hr | congestion=Medium
    green_seconds=53.9s
    predicted_volume -> 15m=3431.16 | 2h=1475.47 | 4h=4677.03
    Moderate congestion with 229 vehicles and speed 74.4 km/h. Green duration set to 54s.
    -> Monitor closely; adjust green duration to 54s if needed.

  CAM_012 | pagi_cctv_013_20260614_081117.mp4
    6/14/2026 8:11:17 | Morning Rush
    lat=-6.234053  lon=106.568393
    weather=Cloudy 28.4C
    vc=268 veh | vol=5520 veh/hr | congestion=Medium
    green_seconds=54.2s
    predicted_volume -> 15m=3651.49 | 2h=1523.95 | 4h=4474.6
    Moderate congestion with 268 vehicles and speed 81.0 km/h. Green duration set to 54s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 54s if needed.

  CAM_007 | pagi_cctv_014_20260518_072255.mp4
    5/18/2026 6:23:39 | Morning Rush
    lat=-6.2194495  lon=106.6572624
    weather=Cloudy 25.2C
    vc=36 veh | vol=7860 veh/hr | congestion=Medium
    green_seconds=55.9s
    predicted_volume -> 15m=5038.54 | 2h=1800.54 | 4h=4425.06
    Moderate congestion with 36 vehicles and speed 28.5 km/h. Green duration set to 56s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 56s if needed. Consider pre-emptive signal adjustment.

  CAM_008 | pagi_cctv_015_20260518_072703.mp4
    5/18/2026 6:39:21 | Morning Rush
    lat=-6.223512  lon=106.623845
    weather=Cloudy 25.2C
    vc=73 veh | vol=1920 veh/hr | congestion=Severe
    green_seconds=90.0s
    predicted_volume -> 15m=1456.7 | 2h=1452.75 | 4h=4424.59
    Severe congestion detected with 22 queued vehicles. Speed dropped to 23.3 km/h indicating traffic breakdown. Green duration extended to 90s to help dissipate the queue. Peak-hour (Morning Rush) increases traffic demand.
    -> Activate emergency traffic control and extend green phase to 90s. Clear queue buildup immediately.

  CAM_004 | pagi_cctv_016_20260614_084327.mp4
    6/14/2026 8:43:27 | Morning Rush
    lat=-6.191635  lon=106.730124
    weather=Cloudy 28.5C
    vc=34 veh | vol=3540 veh/hr | congestion=Low
    green_seconds=41.4s
    predicted_volume -> 15m=3190.85 | 2h=1704.69 | 4h=4768.38
    Traffic is stable with low density (28.5%) and speed 80.9 km/h. Keep default green duration (41s). Peak-hour (Morning Rush) increases traffic demand.
    -> Maintain normal operations with default green duration (41s).

  CAM_002 | pagi_cctv_017_20260614_090631.mp4
    6/14/2026 9:06:31 | Daytime
    lat=-6.2131428  lon=106.683766
    weather=Cloudy 28.5C
    vc=72 veh | vol=4080 veh/hr | congestion=Medium
    green_seconds=51.1s
    predicted_volume -> 15m=3395.65 | 2h=1467.24 | 4h=4897.16
    Moderate congestion with 72 vehicles and speed 64.8 km/h. Green duration set to 51s.
    -> Monitor closely; adjust green duration to 51s if needed.

  CAM_001 | pagi_cctv_018_20260614_090735.mp4
    6/14/2026 9:07:35 | Daytime
    lat=-6.1911513  lon=106.744189
    weather=Cloudy 28.4C
    vc=11 veh | vol=1500 veh/hr | congestion=Low
    green_seconds=40.7s
    predicted_volume -> 15m=422.7 | 2h=1150.55 | 4h=3982.82
    Traffic is stable with low density (9.2%) and speed 55.2 km/h. Keep default green duration (41s).
    -> Maintain normal operations with default green duration (41s).

  CAM_012 | pagi_cctv_019_20260614_080343.mp4
    6/14/2026 8:03:43 | Morning Rush
    lat=-6.234053  lon=106.568393
    weather=Cloudy 28.4C
    vc=64 veh | vol=4140 veh/hr | congestion=Medium
    green_seconds=48.6s
    predicted_volume -> 15m=3252.89 | 2h=1310.0 | 4h=4580.49
    Moderate congestion with 64 vehicles and speed 86.1 km/h. Green duration set to 49s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 49s if needed.

  CAM_003 | pagi_cctv_020_20260614_084403.mp4
    6/14/2026 8:44:03 | Morning Rush
    lat=-6.191535  lon=106.753361
    weather=Cloudy 28.4C
    vc=16 veh | vol=4500 veh/hr | congestion=Low
    green_seconds=33.8s
    predicted_volume -> 15m=3944.53 | 2h=1955.03 | 4h=4289.9
    Traffic is stable with low density (13.6%) and speed 96.5 km/h. Keep default green duration (34s). Peak-hour (Morning Rush) increases traffic demand.
    -> Maintain normal operations with default green duration (34s).

  CAM_009 | pagi_cctv_021_20260614_090559.mp4
    6/14/2026 9:05:59 | Daytime
    lat=-6.226591  lon=106.616335
    weather=Cloudy 28.9C
    vc=33 veh | vol=8220 veh/hr | congestion=Low
    green_seconds=47.7s
    predicted_volume -> 15m=5472.48 | 2h=1811.94 | 4h=4647.27
    Traffic is stable with low density (27.8%) and speed 48.4 km/h. Keep default green duration (48s).
    -> Maintain normal operations with default green duration (48s).

  CAM_004 | pagi_cctv_022_20260614_090032.mp4
    6/14/2026 9:00:32 | Daytime
    lat=-6.191635  lon=106.730124
    weather=Cloudy 28.5C
    vc=179 veh | vol=4260 veh/hr | congestion=Medium
    green_seconds=47.7s
    predicted_volume -> 15m=3423.46 | 2h=1350.9 | 4h=4656.8
    Moderate congestion with 179 vehicles and speed 81.9 km/h. Green duration set to 48s.
    -> Monitor closely; adjust green duration to 48s if needed.

  CAM_007 | pagi_cctv_023_20260614_090010.mp4
    6/14/2026 9:00:10 | Daytime
    lat=-6.2024517  lon=106.705216
    weather=Cloudy 28.5C
    vc=11 veh | vol=2160 veh/hr | congestion=Low
    green_seconds=37.5s
    predicted_volume -> 15m=1006.29 | 2h=1936.73 | 4h=4151.12
    Traffic is stable with low density (9.4%) and speed 71.4 km/h. Keep default green duration (38s).
    -> Maintain normal operations with default green duration (38s).

  CAM_012 | pagi_cctv_024_20260614_083635.mp4
    6/14/2026 8:36:35 | Morning Rush
    lat=-6.234053  lon=106.568393
    weather=Cloudy 29.3C
    vc=235 veh | vol=4680 veh/hr | congestion=High
    green_seconds=59.7s
    predicted_volume -> 15m=2841.9 | 2h=1454.04 | 4h=4632.91
    High traffic density with 7 queued vehicles and speed 76.2 km/h. Green duration adjusted to 60s. Peak-hour (Morning Rush) increases traffic demand.
    -> Increase signal optimization; set green duration to 60s. Focus on bottleneck queue reduction.

  CAM_010 | pagi_cctv_025_20260614_085807.mp4
    6/14/2026 8:58:07 | Morning Rush
    lat=-6.219451  lon=106.657065
    weather=Cloudy 28.9C
    vc=252 veh | vol=7560 veh/hr | congestion=High
    green_seconds=65.6s
    predicted_volume -> 15m=4592.45 | 2h=1805.24 | 4h=4628.4
    High traffic density with 6 queued vehicles and speed 39.0 km/h. Green duration adjusted to 66s. Peak-hour (Morning Rush) increases traffic demand.
    -> Increase signal optimization; set green duration to 66s. Focus on bottleneck queue reduction.

  CAM_002 | pagi_cctv_026_20260614_083559.mp4
    6/14/2026 8:35:59 | Morning Rush
    lat=-6.2131428  lon=106.683766
    weather=Cloudy 28.5C
    vc=38 veh | vol=3780 veh/hr | congestion=Low
    green_seconds=45.7s
    predicted_volume -> 15m=3525.39 | 2h=1437.94 | 4h=4966.55
    Traffic is stable with low density (32.1%) and speed 64.6 km/h. Keep default green duration (46s). Peak-hour (Morning Rush) increases traffic demand.
    -> Maintain normal operations with default green duration (46s).

  CAM_008 | pagi_cctv_027_20260614_085504.mp4
    6/14/2026 8:55:04 | Morning Rush
    lat=-6.2142883  lon=106.68203
    weather=Cloudy 28.5C
    vc=501 veh | vol=10020 veh/hr | congestion=Medium
    green_seconds=58.4s
    predicted_volume -> 15m=5320.77 | 2h=1896.36 | 4h=4448.5
    Moderate congestion with 501 vehicles and speed 60.0 km/h. Green duration set to 58s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 58s if needed.

  CAM_007 | pagi_cctv_028_20260614_083354.mp4
    6/14/2026 8:33:54 | Morning Rush
    lat=-6.2024517  lon=106.705216
    weather=Cloudy 28.5C
    vc=164 veh | vol=4860 veh/hr | congestion=Medium
    green_seconds=48.3s
    predicted_volume -> 15m=3790.35 | 2h=1447.11 | 4h=4674.97
    Moderate congestion with 164 vehicles and speed 78.9 km/h. Green duration set to 48s. Peak-hour (Morning Rush) increases traffic demand.
    -> Monitor closely; adjust green duration to 48s if needed.

  CAM_010 | siang_cctv_001_20260518_163906.mp4
    5/18/2026 15:49:02 | Daytime
    lat=-6.191542  lon=106.753315
    weather=Rain 29.9C
    vc=275 veh | vol=5520 veh/hr | congestion=High
    green_seconds=63.9s
    predicted_volume -> 15m=3571.9 | 2h=1661.15 | 4h=4752.91
    High traffic density with 7 queued vehicles and speed 54.7 km/h. Green duration adjusted to 64s. Rain may reduce road friction and visibility.
    -> Increase signal optimization; set green duration to 64s. Focus on bottleneck queue reduction.

  CAM_010 | siang_cctv_002_20260614_163126.mp4
    6/14/2026 16:31:26 | Evening Rush
    lat=-6.219451  lon=106.657065
    weather=Rain 29.6C
    vc=215 veh | vol=12900 veh/hr | congestion=Medium
    green_seconds=59.0s
    predicted_volume -> 15m=5294.05 | 2h=1719.54 | 4h=4577.73
    Traffic is dense but still maintaining partial flow stability. Green duration set to 59s. Peak-hour (Evening Rush) increases traffic demand. Rain may reduce road friction and visibility.
    -> Monitor closely; adjust green duration to 59s if needed.

  CAM_003 | siang_cctv_003_20260518_165921.mp4
    5/18/2026 16:17:21 | Evening Rush
    lat=-6.2225065  lon=106.6394746
    weather=Clear 29.7C
    vc=19 veh | vol=420 veh/hr | congestion=Severe
    green_seconds=70.6s
    predicted_volume -> 15m=970.56 | 2h=1474.76 | 4h=3790.76
    Severe congestion detected with 10 queued vehicles. Speed dropped to 6.6 km/h indicating traffic breakdown. Green duration extended to 71s to help dissipate the queue. Peak-hour (Evening Rush) increases traffic demand.
    -> Activate emergency traffic control and extend green phase to 71s. Clear queue buildup immediately.

  CAM_005 | siang_cctv_004_20260518_170659.mp4
    5/18/2026 16:13:00 | Evening Rush
    lat=-6.2142883  lon=106.6820298
    weather=Clear 29.9C
    vc=256 veh | vol=14880 veh/hr | congestion=High
    green_seconds=60.3s
    predicted_volume -> 15m=4965.44 | 2h=1714.93 | 4h=4722.17
    High traffic density with 1 queued vehicles and speed 29.3 km/h. Green duration adjusted to 60s. Peak-hour (Evening Rush) increases traffic demand.
    -> Increase signal optimization; set green duration to 60s.

  CAM_011 | siang_cctv_005_20260518_171425.mp4
    5/18/2026 16:24:23 | Evening Rush
    lat=-6.191635  lon=106.730124
    weather=Clear 29.9C
    vc=362 veh | vol=8340 veh/hr | congestion=Severe
    green_seconds=90.0s
    predicted_volume -> 15m=4073.9 | 2h=1784.67 | 4h=4665.11
    Severe congestion detected with 109 queued vehicles. Speed dropped to 22.8 km/h indicating traffic breakdown. Green duration extended to 90s to help dissipate the queue. Peak-hour (Evening Rush) increases traffic demand.
    -> Activate emergency traffic control and extend green phase to 90s. Clear queue buildup immediately.

  CAM_003 | siang_cctv_006_20260614_170915.mp4
    6/14/2026 17:09:15 | Evening Rush
    lat=-6.191535  lon=106.753361
    weather=Rain 28.7C
    vc=249 veh | vol=10260 veh/hr | congestion=High
    green_seconds=68.9s
    predicted_volume -> 15m=5172.76 | 2h=1765.07 | 4h=4565.29
    High traffic density with 8 queued vehicles and speed 38.8 km/h. Green duration adjusted to 69s. Peak-hour (Evening Rush) increases traffic demand. Rain may reduce road friction and visibility.
    -> Increase signal optimization; set green duration to 69s. Focus on bottleneck queue reduction.

  CAM_011 | siang_cctv_007_20260518_160452.mp4
    5/18/2026 15:08:58 | Daytime
    lat=-6.191635  lon=106.730124
    weather=Cloudy 30.5C
    vc=352 veh | vol=7020 veh/hr | congestion=Medium
    green_seconds=55.6s
    predicted_volume -> 15m=4723.02 | 2h=1949.57 | 4h=4657.33
    Moderate congestion with 352 vehicles and speed 58.0 km/h. Green duration set to 56s.
    -> Monitor closely; adjust green duration to 56s if needed.

  CAM_011 | siang_cctv_008_20260518_151934.mp4
    5/18/2026 14:23:40 | Daytime
    lat=-6.191635  lon=106.730124
    weather=Rain 31.3C
    vc=16 veh | vol=7740 veh/hr | congestion=Low
    green_seconds=38.9s
    predicted_volume -> 15m=5072.38 | 2h=1633.66 | 4h=4553.98
    Traffic is stable with low density (14.1%) and speed 71.7 km/h. Keep default green duration (39s). Rain may reduce road friction and visibility.
    -> Maintain normal operations with default green duration (39s).

  CAM_004 | siang_cctv_009_20260614_170730.mp4
    6/14/2026 17:07:30 | Evening Rush
    lat=-6.191635  lon=106.730124
    weather=Rain 29.2C
    vc=256 veh | vol=9300 veh/hr | congestion=Medium
    green_seconds=52.7s
    predicted_volume -> 15m=5385.18 | 2h=1807.35 | 4h=4415.88
    Moderate congestion with 256 vehicles and speed 65.4 km/h. Green duration set to 53s. Peak-hour (Evening Rush) increases traffic demand. Rain may reduce road friction and visibility.
    -> Monitor closely; adjust green duration to 53s if needed.

  CAM_012 | siang_cctv_010_20260614_171050.mp4
    6/14/2026 17:10:50 | Evening Rush
    lat=-6.234053  lon=106.568393
    weather=Rain 29.9C
    vc=342 veh | vol=6840 veh/hr | congestion=High
    green_seconds=62.4s
    predicted_volume -> 15m=4064.4 | 2h=1739.05 | 4h=4540.67
    High traffic density with 8 queued vehicles and speed 70.1 km/h. Green duration adjusted to 62s. Peak-hour (Evening Rush) increases traffic demand. Rain may reduce road friction and visibility.
    -> Increase signal optimization; set green duration to 62s. Focus on bottleneck queue reduction.

  CAM_005 | siang_cctv_011_20260614_171352.mp4
    6/14/2026 17:13:52 | Evening Rush
    lat=-6.2225065  lon=106.639475
    weather=Rain 29.6C
    vc=2 veh | vol=180 veh/hr | congestion=High
    green_seconds=49.1s
    predicted_volume -> 15m=1180.29 | 2h=1591.7 | 4h=4011.57
    High traffic density with 0 queued vehicles and speed 2.5 km/h. Green duration adjusted to 49s. Peak-hour (Evening Rush) increases traffic demand. Rain may reduce road friction and visibility.
    -> Increase signal optimization; set green duration to 49s.

  CAM_007 | siang_cctv_012_20260614_165224.mp4
    6/14/2026 16:52:24 | Evening Rush
    lat=-6.2024517  lon=106.705216
    weather=Rain 29.2C